### ISSUE TITLE
Toevoeging van 'Hout' aan codelijst "BestratingVerhardingTypeValue"

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Discussion#106]
Volgens ervaring GGINO-vervolgtraject Aalst (GGINO 1.1 en 1.2): er zijn delen van het openbaar domein die een houten voorkomen hebben. (vb: ondergrond van de zitbank ter hoogte van de Zeebergbrug in Aalst)

-- Definition --
Verhardingstype bestaande uit duurzaam verankerde houten onderdelen.

**Comment by tibaert** [comment]
Er was ook al geopperd voor "Vondelpad" toe te voegen. Dit kan eventueel een subcategorie zijn van "Hout". 
Te bespreken tijdens diepteoverleg Terreindeel.

**Comment by jensscheerlinck** [comment]
Besproken tijdens webcast op 26 september 2018
Voorstel van oplossing werd aanvaard:

Voor de taxonomische indeling van onbegroeid voorkomen werd gealigneerd op standaardbestek 250 van agentschap wegen en verkeer.

Geïmplementeerd in commit: https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/c0400668b0be709bf67f73f53e0ab5f67c7958c1

Resultaat: https://data.vlaanderen.be/doc/applicatieprofiel/onbegroeidvoorkomencataloog/
