### ISSUE TITLE
Halfverharding

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Discussion#108]
Volgens ervaring GGINO-vervolgtraject Aalst (GGINO 1.1 en 1.2): Het type "halfverharding" is een verzamelbegrip voor meer specifieke types als "GRAVEL, DOLOMIETSTEENSLAG, STEENSLAG, STEENSLAG_ROLGRIND en TERNAIR MENGSEL". In GGINO 1.2 hebben we dit gewoon als extra type onder de codelijst van BedekkingTypeValue geplaatst, en hebben we er niet voor gekozen om een nieuwe klasse te maken.

-- Definition --
Niet gecompacteerd en op niet-duurzame wijze verankerd met het aardoppervlak en specifiek bedoeld voor bedekkingstypes zoals GRAVEL, DOLOMIETSTEENSLAG, STEENSLAG, STEENSLAG_ROLGRIND en TERNAIR MENGSEL.
-- Description --
NOTE Algemeen attribuut dat kan gekozen worden wanneer geen verder detailniveau gewenst is.
NOTE Bron definitie: GRB-skeletaanvulling detail: WSV1: Soort verharding/bedekking
NOTE: Dit type kan gebruikt worden binnen corridor-gebieden, terwijl in surplusgebieden dan kan gekozen worden voor de gedetailleerde bedekkingstypes GRAVEL, DOLOMIETSTEENSLAG, STEENSLAG, STEENSLAG_ROLGRIND en TERNAIR MENGSEL.

**Comment by tibaert** [comment]
Dit kan worden opgelost door gebruik te maken van een taxonomie voor Fysiekvoorkomen. 
Te bespreken tijdens diepteoverleg Terreindeel.

**Comment by jensscheerlinck** [comment]
Besproken tijdens webcast op 26 september 2018
Voorstel van oplossing werd aanvaard:

Voor de taxonomische indeling van onbegroeid voorkomen werd gealigneerd op standaardbestek 250 van agentschap wegen en verkeer.

Geïmplementeerd in commit: https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/c0400668b0be709bf67f73f53e0ab5f67c7958c1

Resultaat: https://data.vlaanderen.be/doc/applicatieprofiel/onbegroeidvoorkomencataloog/
