### ISSUE TITLE
Extra attributen voor Vocabularium Besluit in de context van de Vlaamse Codex als LOD

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#124]
Voor de implementatie van de Vlaamse Codex als Linked Open Data is er nood om een aantal relaties tussen wetgevende documenten te beschrijven, die specialisaties zijn van bestaande ELI relaties zoals ook reeds opgenomen in het Besluit Publicatie AP.

Het gaat om de volgende relaties

- Heft op/opgeheven bij: specialisatie van eli:repeals/repealed_by 
- Trekt in/ingetrokken bij: specialisatie van eli:repeals/repealed_by 
- Vervangt/vervangen bij: specialisatie van eli:repeals/repealed_by 

In de ELI definitie voor eli:repeals staat:

> Indicates that this legal resource or legal expression completely cancels, abrogates or replaces another.

Bij de specialisaties gaat het respectievelijk om 'cancels', 'abrogates' en 'replaces'. 

- Voegt in/ingevoegd bij: specialisatie van eli:amends/amended_by

ELI definitie voor amends:
> Indicates that this resource introduces legal changes in another resource. For modifications that don’t have a legal impact, use eli:corrects.
Bij de specialisatie 'voegt in' gaat het om een toevoeging op de reeds bestaande tekst, zonder de bestaande tekst aan te passen. Bijvoorbeeld: invoegen extra paragraaf bij artikel, invoegen extra artikel bij hoofdstuk/document.

- Bekrachtigt/bekrachtigd_bij: nieuwe relatie (niet gedefinieerd in ELI):

Voorstel definitie:

> Betekent dat dit document instemt met een ander type document waardoor dat laatste volledige rechtskracht krijgt. De bekrachtiging is in dit geval een opschortende voorwaarde.

**Comment by brechtvdv** [comment]
@jensscheerlinck Ik stel voor om Bekrachtigt/bekrachtigd_bij te laten specialiseren van 'Changes/changed_by' aangezien dit om legale impact gaat?
Opschortende voorwaarde zou ik dan mee in de definitie zetten.

**Comment by jensscheerlinck** [comment]
@brechtvdv OK :-)

**Comment by brechtvdv** [comment]
Voegt in/ingevoegd bij → is er altijd legale impact hier?

**Comment by brechtvdv** [comment]
@jensscheerlinck

**Comment by jensscheerlinck** [comment]
@brechtvdv ja dat is steeds het geval

**Comment by brechtvdv** [comment]
Is nog niet gepubliceerd, maar wel geïmplementeerd in EA (OSLO-Besluit vocabularium)

**Comment by mvanbrab** [comment]
Issue indicatief heropend tot aan publicatie na afspraak hierover.

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0

**Comment by YvesMeersmans** [comment]
Issue heropend om de specialisatie van **bekrachtigt/bekrachtigd bij** te herbekijken. Momenteel is dit respectievelijk **eli:changes/eli:changed_by**.

De huidige definitie van bekrachtigt is _Instemming onder opschortende voorwaarde van een rechtsgrond of legale verschijningsvorm op een andere zodat deze laatste volledige rechtskracht krijgt._

**eli:commences/eli:commenced_by** lijkt hier beter bij aan te sluiten: Indicates that this legal resource sets another legal resource into force.
