### ISSUE TITLE
Hernoeming relatie lidmaatschap en fractie

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLO-Discussion#126]
Lidmaatschap **binnen** Fractie vervangen door **is lidmaatschap bij**

Zie: http://data.vlaanderen.be/doc/applicatieprofiel/mandatendatabank#Lidmaatschap%3Abinnen

**Comment by mvanbrab** [comment]
Is nu zo d.m.v. tage "target-label-nl" op associatepijl "isLidVan" (in combinatie met de associatieklasse "OSLO-Organisatie::Lidmaatschap"). Mag gesloten worden na nieuwe publicatie.

**Comment by mvanbrab** [comment]
Is opgelost in EA repository.

**Comment by mvanbrab** [comment]
Issue indicatief heropend tot aan publicatie na afspraak hierover.

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0
