### ISSUE TITLE
Predikaten toevoegen aan legale verschijningsvorm

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLO-Discussion#127]
Legale verschijningsvorm bevat niet alle nodige predikaten zoals bij Rechtsgrond, namelijk:
* Corrigeert / gecorrigeerd door
* Verandert / veranderd door
* Citeert / geciteerd door
* Aangenomen door (eli:passed_by)

De eerste 3 predikaten mogen aan Legale verschijningsvorm toegevoegd worden volgens ELI.

_Aangenomen door_ is enkel toepasbaar op Rechtsgrond.

**Comment by brechtvdv** [comment]
Is opgelost mbv "UnieRGLV" die deze predikaten zowel op Legale Verschijningsvorm als Rechtsgrond zet.

**Comment by mvanbrab** [comment]
Issue indicatief heropend tot aan publicatie na afspraak hierover.

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0
