### ISSUE TITLE
Relatie tussen Legale verschijningsvormen (Besluit en Artikel)

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLO-Discussion#128]
Om aan te duiden dat een artikel onderdeel is van een besluit (in z'n verschijningsvorm) en omgekeerd kan respectievelijk eli:is_part_of en eli:has_part **niet** gebruikt worden, aangezien dit enkel op Legale Expressies van toepassing is.

Voorstel: dcterms:hasPart en dcterms:isPartOf gebruiken

**Comment by brechtvdv** [comment]
We gebruiken:
* eli:is_part_of en eli:has_part voor de relatie tussen legale verschijningsvorm en legale verschijningsvorm onderdeel
* eli:is_member_of en eli:has_member voor de relatie tussen legale rechtsgrond en legale rechtsgrond onderdeel

**Comment by brechtvdv** [comment]
We hebben eli:has_part / eli:is_part_of behouden op rechtsgrond, omdat deze in de definitie 'fysiek' kan bevatten.
We hebben dcterms:hasPart en dcterms:isPartOf gebruikt tussen Besluit en artikel

**Comment by mvanbrab** [comment]
Was al in orde in EA repository. Zie ook #153 voor verhinderen toepassing deze eli properties op legale verschijningsvorm.

**Comment by mvanbrab** [comment]
Issue indicatief heropend tot aan publicatie na afspraak hierover.

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0
