### ISSUE TITLE
Content negotiation werkt niet bij Besluit ontology

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#129]
curl -H "Accept: application/rdf+xml" http://data.vlaanderen.be/ns/besluit

**Comment by bertvannuffelen** [comment]
bedankt, probleem gespot en issue aangemaakt om het proces meer expliciet te maken.

**Comment by bertvannuffelen** [comment]
opgelost voor nu, maar de toolchain moet nog wel aangepast worden om de garantie te geven dat dit niet meer voorkomt.

**Comment by jensscheerlinck** [comment]
Nieuwe versie van toolchain deployed via CircleCI
Probleem zou niet meer mogen voorkomen
