### ISSUE TITLE
gebruiksnota: Enkel te gebruiken ...

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#131]
In het applicatieprofiel van de besluit staat de volgende gebruiksnota:

```
Enkel te gebruiken wanneer de voorzitter tijdens de behandeling van het agendapunt verschilt van de voorzitter van de zitting.
```

Dit is wel moeilijk af te dwingen en maakt de semantiek heel erg moeilijk. Namelijk de semantiek is niet meer op zich zelf staand, maar afhankelijk gemaakt t.o.v. de interpretatie van informatie ergens anders in de informatiestruktuur. Bovendien is de nota eigenlijk overbodig.

De definitie voor de eigenschap waarop deze gebruiksnota is gegeven stelt:
"De mandataris die de rol als voorzitter heeft gedurende de behandeling van het agendapunt. "
De kardinaliteit stelt dat er slechts 1 voorzitter kan zijn. 

Of dat deze nu dezelfde is of niet als degene die de voorzitter is van de vergadering waarin dit agendapunt wordt behandeld dat maakt niet uit voor de betekenis van deze eigenschap. 

Daarnaast als je wil weten wie de voorzitter van een agendapunt is dan pas je het algoritme toe:
`
De voorzitter van een agendapunt is 
     ofwel expliciet gegeven
     ofwel niet aanwezig en dan nemen we de voorzitter van de behandelde vergadering, indien gegeven.                 
`

Als je toch het zou willen toevoegen als een beperking in de context van een applicatieprofiel. Dan zou ik de verwoording van de gebruiksnota veranderen. De gebruiksnota sluit vormen van datastructuren uit die semantisch equivalent zijn, niet schadelijk, enkel meer verbose. En dat laatste is niet nodig. Ik denk dat dit eerder een beperking is die je kan opleggen aan een implementatie dan aan een applicatieprofiel.

**Comment by brechtvdv** [comment]
Wat denk je van 'Enkel' weg te laten uit de gebruiksnota?

**Comment by mvanbrab** [comment]
Dit geldt ook niet alleen voor de voorzitter, maar ook voor de secretaris.
We passen beide usageNotes aan als volgt:
"Verplicht te gebruiken wanneer de voorzitter tijdens behandeling van het agendapunt verschilt van de voorzitter van de zitting; anders optioneel."
"Verplicht te gebruiken wanneer de secretaris tijdens behandeling van het agendapunt verschilt van de secretaris van de zitting; anders optioneel."

**Comment by mvanbrab** [comment]
Beschikbaar in EA repository.

**Comment by mvanbrab** [comment]
Issue indicatief heropend tot aan publicatie na afspraak hierover.

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0
