### ISSUE TITLE
besluit > DUL

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#133]
Beste,

wat is de reden voor de verwijzing naar 
<http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#hasParticipant>

Wat is meerwaarde t.o.v. de informatie die nu al aanwezig is.

mvg,

Bert

**Comment by DieterDePaepe** [comment]
Dag Bert,

voor alle termen hebben we gekeken of er reeds bestaande (en stabiele) vocabularia waren waarmee we konden afstemmen, zoals de regels van linked data ons voorleggen.

De DUL#hasParticipant was een twijfelgeval of deze voldeed of niet. De semantiek ervan leek overeen te komen met wat we nodig hadden, en de ontology design patterns zijn een gevestigde academische waarde. Uiteindelijk is er gekozen door een link te leggen met DUL#hasParticipant ipv de term rechtstreeks te gebruiken, omdat academische vocabularia niet altijd even stabiel blijken te zijn. Zo hadden we een gegarandeerde stabiele (Vlaamse) uri, maar wel gelinkt met bestaande ontologies.

Persoonlijk ben ik zelf geen fan van de ontology design patterns, maar ik zag geen reden om niet te linken naar de term.

**Comment by bertvannuffelen** [comment]
Dag Dieter,

Ik stel die vraag omdat hasParticipant erg generiek is en dat je dus in verschillende domeinen gelijkaardige terminologie zal tegen komen. En dan vraag ik me af of dit wel goed idee is om te verwijzen naar varianten van generieke vocabularia/ontologiën.  Waarom iets toevoegen dat slechts beperkte meerwaarde heeft en dit heeft mogelijks een weerslag op andere vocabularia.


Het is trouwens geen free-lunch: omdat DUL een OWL ontology is importeer je niet alleen de betekenis maar ook alle geassocieerde logica:

```
<owl:ObjectProperty rdf:about="http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#hasParticipant"><rdfs:label xml:lang="en">has participant</rdfs:label><rdfs:label xml:lang="it">ha come partecipante</rdfs:label><rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A relation between an object and a process, e.g. 'John took part in the discussion', 'a large mass of snow fell during the avalanche', or 'a cook, some sugar, flour, etc. are all present in the cooking of a cake'.</rdfs:comment><rdfs:isDefinedBy rdf:resource="http://www.ontologydesignpatterns.org/ont/dul/DUL.owl"/><rdfs:domain rdf:resource="http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#Event"/><rdfs:range rdf:resource="http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#Object"/><rdfs:subPropertyOf rdf:resource="http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#associatedWith"/><owl:inverseOf rdf:resource="http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#isParticipantIn"/></owl:ObjectProperty>
```

m.a.w. 
de inverse definitie, domain en range en mogelijks nog andere aspecten.

Ik ben zeer voorzichtig met het importeren van afhankelijkheden die op OWL gebaseerd zijn: zij zetten sterke beperkingen op de model, en creeëren mogelijks zijeffecten (*) die je niet gewenst zijn. Om dit te onderzoeken moeten we een OWL reasoner gebruiken die alle informatie samen neemt en daarmee consistentie checken. 

Dit is trouwens dé uitdaging van hergebruik van OWL ontologiën. Doordat ze zo'n sterke uitdrukking zijn van hoe de wereld er moet uitzien, is het lastig om ze te hergebruiken in een context die net iets anders is. Dat is de reden waarom ik steeds een gelaagde aanpak zie: vocabularia binden termen aan menselijke definities, met zo breed mogelijke domain en range uitdrukkingen, applicatieprofielen zijn sterker en zetten de relaties meer vast, en tenslotte het eigenlijke model welke een instantie is van het applicatieprofiel.  Enkel door deze gelaagdheid kan hergebruik ontstaan. En spijtig genoeg zijn OWL ontologiën dikwijls enkel het laatste, en voorzien ze niet in die gelaagdheid, waardoor hun hergebruik erg beperkt wordt. 

Suggestie voor hier is om niet een relatie met een logica semantiek te nemen, maar eentje waarin dit aan de gebruiker is. bv. skos:broaderMatch: dat drukt uit dat het een gelijkaardig concept is met een breedere betekenis, maar het drukt geen logische relatie (rdfs:subpropertyOf) uit. 

Hiermee importeer je dus niet de ontology, maar verwijs je naar gelijkaardige concepten. (SKOS maakt dit heel duidelijk: de skos relaties vormen geen basis voor een logisch theorie, maar enkel een aanduiding van gemeenschappelijke betekenis.)

Dit is voor mij een ontwikkelingsprincipe van de OSLO modellen waarover klaarheid moet gebracht worden. Met de veelheid aan modellen moeten we misschien beter wat waakzamer en voorzichtiger zijn en bepaalde keuzes enkel in applicatieprofielen opnemen en niet in het vocabularium.

(*) een zij-effect is bij voorbeeld doordat er staat dat 
<http://data.vlaanderen.be/ns/besluit#heeftAanwezige> een subproperty is van zowel 
<http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#hasParticipant> als        prov:wasAssociatedWith.
Dit betekent dat er slecht een instantie van deze relatie kan bestaan als beide superproperties niet disjoint zijn. Dat moet bewezen worden.  En als bewezen wordt dat beide eigenschappen disjoint zijn, dan kan bovenstaande eigenschap helemaal niet gebruikt worden.

**Comment by DieterDePaepe** [comment]
Dag Bert,

ik ga akkoord met de punten die je aanhaalt. Ik denk dat de zij-effecten effectief onderzocht zijn toen OSLO ontwikkeld werd, en er toen geen conflicten waren. Het is al even geleden wel, en ben niet meer zeker tot welk detail dit gebeurd is wel.

Ik zou akkoord gaan met zowel de huidige overerving te bewaren, als met die te vervangen door skos:broaderMatch (al dan niet preventief of na verder onderzoek van mogelijke conflicten). Ik laat de keuze aan de huidige beheerders over. (cc @brechtvdv )

**Comment by brechtvdv** [comment]
Bedankt @bertvannuffelen om jouw visie te delen.
Ik ga de logische relatie met de DUL ontologie eruit halen. 

Sidenote: @mvanbrab gaat een experiment opzetten om skos-relaties toe te voegen met onze toolchain.

**Comment by mvanbrab** [comment]
Ik heb intussen dit experiment gedaan (althans voor EA-to-RDF).

Als je in de OSLO-EA-to-RDF configuratie voor voc dit toevoegt bij de internalMappings:

    {
      tag: "broadMatch",
      property: "http://www.w3.org/2004/02/skos/core#broadMatch",
      mandatory: false
    }

en in EA één van de parentURI tags voor de betreffende property vervangt door een broadMatch tag met dezelfde waarde, dan krijg je in **besluit.ttl** voor deze property dit:

    rdfs:subPropertyOf prov:wasAssociatedWith ;
    skos:broadMatch "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#hasParticipant" .

in plaats van:

    rdfs:subPropertyOf <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#hasParticipant>,
        prov:wasAssociatedWith .

Om dit in de **html** van het vocabularium te zien te krijgen, is een aanpassing in OSLO-SpecificationGenerator (en/of de template voor vocabularia) nodig. Daarvoor zou een afspraak nodig zijn hoe we dit presenteren…

Ik stel voor dat we dit doen als dit prioritair wordt.

**Comment by brechtvdv** [comment]
@mvanbrab Heb je ticket aangemaakt voor 'een aanpassing in OSLO-SpecificationGenerator (en/of de template voor vocabularia) nodig.'? Lijkt me beter om de feature los van deze issue te behandelen.

**Comment by mvanbrab** [comment]
Deed ik zopas...

**Comment by mvanbrab** [comment]
Issue indicatief heropend tot aan publicatie na afspraak hierover.

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0
