### ISSUE TITLE
Klasse http://data.vlaanderen.be/ns/besluit#Besluit

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#135]
1. De definitie is niet helemaal correct.

Definitie | De authentieke  schriftelijke neerslag van een beslissing van een bestuursorgaan. Deze  beslissing houdt een rechtshandeling in waarbij sprake is van een beoogd  rechtsgevolg.

Het aspect "authentieke schriftelijke neerslag" van een beslissing van een bestuursorgaan, houdt in dat de beslissing van het bestuursorgaan enkel kan bestaan, of realiteit wordt in zijn gedocumenteerde vorm, dat van deze url enkel het type http://data.vlaanderen.be/doc/besluit/besluit_xxx zou bestaan en niet de id http://data.vlaanderen.be/id/besluit/besluit_xxx, waarschijnlijk vanuit de rationale dat enkel gepubliceerde beslissingen kracht van wet hebben. 
Dit blijkt niet correct te zijn. Bijvoorbeeld voor eedafleggingen, die al van kracht zijn van vlak na de eedaflegging, dus alvorens er een gedocumenteerde versie van bestaat.

Deze definitie zou dan ook moeten aangepast worden, ruimer dan de schriftelijke neerslag.

2. Zou deze klasse ook subclass van http://purl.org/dc/terms/RightsStatement kunnen zijn?

Vaak gaan Besluiten over werkelijke dingen. Daarvoor hebben wij de property:

dossier:certifiëert a owl:ObjectProperty;
        rdfs:range prov:Entity;
        rdfs:domain dcterms:RightsStatement;
        owl:inverseOf dcterms:rights .
 
En gebruiken we dcterms:rightsHolder om naar "vergunningshouders te wijzen

**Comment by brechtvdv** [comment]
1. Dit klopt niet. Een beslissing is inderdaad van kracht voordat het effectief neergeschreven is. Daarvoor wordt in het applicatieprofiel van besluit (http://data.vlaanderen.be/doc/applicatieprofiel/besluit-publicatie) verwezen naar "Rechtsgevolg (Besluit)".
De eedaflegging zorgt ervoor dat het Rechtsgevolg in voege is, waarna later dit neergeschreven wordt in een Besluit.

2. Je zou inderdaad Besluit kunnen subclassen hiervan (cfr. "a legal document giving official permission to do something with a resource").

**Comment by brechtvdv** [comment]
@gezever dcterms:rightsHolder kan denk ik best gebruikt worden als parent class van "vergunningshouder", omdat deze deels "owner" zijn van de vergunning, naast het lokaal bestuur.

Kan dit ticket gesloten worden?

**Comment by gezever** [comment]
@brechtvdv 
dcterms:rightsHolder is geen class, maar een property. Een vergunning geeft het recht om iets te doen aan de vergunningshouder. Dit is geenszins het lokaal bestuur. Het is niet omdat een bestuur een vergunning geeft om te lozen dat deze lokale overheid zelf het recht heeft om te lozen.

**Comment by brechtvdv** [comment]
Inderdaad, ik bedoelde dcterms:rightsHolder als parent property van "vergunningshouder". Het lokaal bestuur kan aangeduid worden via http://data.europa.eu/eli/ontology#passed_by op de rechtsgrond van het besluit.
