### ISSUE TITLE
Blank nodes van locn:Address; Vraag om een property toe te voegen aan "http://data.vlaanderen.be/ns/adres#

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#137]
Zou er een property adres:adresvoorstellingVan owl:inverseOf locn:address kunnen toegevoegd worden aan het adres vocabulair aub? 
Ik denk dat door deze property toe te voegen aan blank nodes van adresvoorstelling (locn:Address) deze makkelijker opzoekbaar worden.

**Comment by gezever** [comment]
###  http://data.vlaanderen.be/ns/adres#adresvoorstellingVan
<http://data.vlaanderen.be/ns/adres#adresvoorstellingVan> rdf:type owl:ObjectProperty ;
                                                          rdfs:domain <http://www.w3.org/ns/locn#Address> ;
                                                          rdfs:range owl:Thing ;
                                                          vann:usageNote "Deze property is tegengesteld aan locn:address. Kan gebruikt worden om te refereren vanuit blank nodes."@nl ;
                                                          rdfs:comment "Legt de link tussen een adresvoorstelling en de resource waaraan deze adresvoorstelling is toegekend."@nl ;
                                                          rdfs:isDefinedBy <http://data.vlaanderen.be/ns/adres> ;
                                                          rdfs:label "Adresvoorstelling van"@nl .

**Comment by gezever** [comment]
###  http://data.vlaanderen.be/ns/adres#adresvoorstellingVan
<http://data.vlaanderen.be/ns/adres#adresvoorstellingVan> rdf:type owl:ObjectProperty ;
                                                          owl:inverseOf locn:address ;
                                                          rdfs:domain locn:Address ;
                                                          rdfs:range owl:Thing ;
                                                          vann:usageNote "Deze property is tegengesteld aan locn:address. Kan gebruikt worden om te refereren vanuit blank nodes."@nl ;
                                                          rdfs:comment "Legt de link tussen een adresvoorstelling en de resource waaraan deze adresvoorstelling is toegekend."@nl ;
                                                          rdfs:isDefinedBy <http://data.vlaanderen.be/ns/adres> ;
                                                          rdfs:label "Adresvoorstelling van"@nl .

**Comment by bertvannuffelen** [comment]
er is een eigenschap http://data.vlaanderen.be/ns/adres#verwijstNaar welke je misschien bedoelt, want locn:address is voor zover ik zie geen onderdeel van het vocabularium.

Daarnaast, ben ik persoonlijk van mening dat we inverse eigenschappen we best niet modelleren. 1 richting is voldoende om een relatie aan te duiden. Het invoeren vereist extra validatie en leidt tot grotere complexiteit zonder meestal een directe meerwaarde. 

Daarnaast is voor mij het vocabularium/applicatieprofiel niet een implementatiemodel, maar een uitwisselingsmodel dat je naar eigen noden kan uitbreiden. Ik bedoel hiermee dat als je OSLO compliant data wil hebben dan moet je de termen van het vocabularium gebruiken volgens de intentionele definities (de semantiek). Daarnaast voor de data moet je ook de identificatoren van de objecten gebruiken. Maar wat je verder doet: of je het beheert als een binair bestand, of eigen uitbreidingen met nieuwe termen voorziet of enkel een subset van het vocabularium gebruikt, dat is aan je eigen beslissing.

Voor basisregisters zoals het adressenregister is er wel een sterke, bijna 1-op-1 verband met het applicatieprofiel adres. Maar voor een gebruiker ervan zoals b.v. het EPC-register kan het misschien volstaan met een beperkte info. Het is zelfs misschien niet meer nodig om gegevens welke een PURI hebben gekregen (zoals de Vlaamse adressen) in alle detail op te slaan, maar enkel te werken met de PURI. En dan wanneer er nood is de gegevens op te halen.

Voor het voorbeeld van het EPC register, kan die bestaan uit een eenvoudige tabel

<http://data.vlaanderen.be/id/gebouw/12321321> vea:epc "256"^^xsd:integer.

Alle andere gegevens over de ligging van het gebouw zijn vindbaar via de PURI. En moeten dus niet worden meegegeven in een uitwisseling. Als je dat toch doet, dan ben je gebonden aan het vocabularium. Echter mijn advies zou zijn om dat zeer voorzichtig te zijn omdat we hier anders misschien data synchronisatie issues kunnen ontstaan. 

Dus terugkomende op je oorspronkelijke vraag ivm. inverse relaties. Ik zou graag de noodzaak verstaan om die in te voeren, maar in mijn ervaring is er eigenlijk zelden nood aan de inverse expliciet te maken tenzij om de menselijke communicatie te vereenvoudigen. 

ps. voor RDF is net niet nodig (querying is richting neutraal), ook voor json-ld is het niet nodig want die hebben een "@reverse" keyword om dit in de context mapping aan te geven.

**Comment by gezever** [comment]
Het gaat o.a.  over menselijke communicatie en distributies van datasets in verschillende formaten. Het gaat ook over rekening houden met het perspectief van de gebruikers van generieke modellen. http://data.vlaanderen.be/ns/adres#verwijstNaar heeft een "vlaams adres" als range en een locn:Address (wat jullie een adresvoorstelling noemen) als domein. Ik wil daarnaast  een verwijzing naar onze eigen business objecten. 
Een verwijzing vanuit een "adresvoorstelling" is in deze ontologie op zijn plaats. Ik zou willen vermijden  dat we deze property in iedere businesspecifieke ontologie die we bij omgeving opstellen, moeten hermodelleren.

**Comment by bertvannuffelen** [comment]
Dat is een relevante usecase.
Het gebruiken van adresvoorstelling in andere toepassingen. 

Dat is dus inderdaad niet gemodelleerd. En open gelaten.

**Comment by bertvannuffelen** [comment]
toch nog een vraagje: waarom relateren naar adresvoorstelling? 
Omvat jou data adressen die buiten het adressenregister vallen?

**Comment by gezever** [comment]
Ik werk momenteel aan het archiveren van dossiers binnen een applicatie voor het aanvragen van een conformiteitsattest voor zendantennes. De data wordt geserialiseerd naar triples en de adressen zitten in één db-veld. Binnen de context van dit project is er geen plaats voor mapping naar het adressenregister. 
Ik gebruik dus een blank node van het type locn:Address met property locn:fullAddress. 
http://data.vlaanderen.be/ns/adres#adresvoorstellingVan stelt me in staat om de relatie naar onze business-objecten te leggen. Een koppeling met het adressenregister kan eventueel later nog met http://data.vlaanderen.be/ns/adres#verwijstNaar. Rechtstreekse koppeling zou ook kunnen met http://data.vlaanderen.be/ns/adres#isToegekendAan, maar daarvan is de range http://data.vlaanderen.be/ns/adres#AdresseerbaarObject.
1. de betekenis van AdresseerbaarObject is niet eenduidig.
in rdfxml luidt dit:
        <ns0:usageNote xml:lang="nl">Waarbij het niveau staat voor de geografische granulariteit vd locator: zo verwijzen locators vh type huisnummer doorgaans naar het gebouw terwijl busnummers naar een deel vh gebouw verwijzen.</ns0:usageNote>
        <rdfs:comment xml:lang="nl">Het niveau waarnaar de locator verwijst.</rdfs:comment>
in html:

Definitie | Geografisch object dat met een adres kan worden geïdentificeerd.
-- | --
Is abstract, ttz het type adresseerbaar object moet altijd worden opgegeven (vb gebouweenheid, perceel).

2. Die rechtstreeks koppeling zou voor mijn part liefst via een property met range owl:Thing of zoiets gaan.
 We hebben allerlei objecten met adressen, ook personen, waarvan ik niet persé adresseerbare objecten wil maken.
3. mbt. die personen zie ik een lacune in de relatie tussen personen en adressen in het Persoon model. Adressen zijn in onze context vaak rol-afhankelijke contactgegevens.

**Comment by gezever** [comment]
Dank je wel voor dit op te nemen trouwens Bert.
Groeten,
Geert

**Comment by mvanbrab** [comment]
My two cents:

UML fragment van de oorspronkelijke vraag (denk ik):

![137](https://user-images.githubusercontent.com/6448245/44985127-785f0280-af7f-11e8-920b-14dd9aa40e50.PNG)
(suggestie - maakt geen deel uit van het huidig vocabularium)

waarbij moet opgemerkt worden dat de huidige OSLO-toolchain owl:inverseOf niet kan genereren. 

Een suggestie tot oplossing die toelaat dat Adresvoorstelling gelinkt wordt aan een Adresserbaar zonder de noodzaak aan een (Belgisch) Adres zou kunnen zijn (met dank aan Bert):

![137a](https://user-images.githubusercontent.com/6448245/44985398-87928000-af80-11e8-9122-7eb3b4b28885.PNG)
(suggestie - maakt geen deel uit van het huidig vocabularium)

waar de oplossing bestaat in de toevoeging van de associatie voorstellingIsToegekendAan, van AdresVoorstelling naar AdresseerbaarObject. Dit veronderstelt dan dat de aanvrager zelf een klasse afleid van AdresseerbaarObject.

**Comment by GeertThijs** [comment]
- Adresvoorstelling is bedoeld als "adreslabel", je zet het ergens bij (in Contactinfo, bij een Gebouw, in een Dossier, op een Brief) om het adres weer te geven zodat het direct gebruikt kan worden (bv op een kaart, op een postetiket) zonder eerst het corresponderende gestructureerd Adres te moeten interpreteren en omzetten in een String.
- Om die reden is Adresvoorstelling niet meer dan een datatype, het heeft geen identiteit en is enkel bepaald door zijn waarde. Bedoeling is om het op te voeren als attribuut van een klasse. Een associatie is dan niet nodig, die is er vanzelf omdat de Adresvoorstelling een attribuut is vh object waar het bijstaat (de zgn ownedattribute relatie in het UML-metamodel). 
-  Hoe je dit implementeert is een andere zaak. in xml-termen: of je plaatst het adres inline bij de data vh gebouw of je werkt met id en idref als je het adres maar één keer in de uitwisseling wil. Gelijkaardige aanpak in rdf met een blank node, al ben ik hier minder mee vetrouwd dus corrigeer me indien dit niet klopt.
- Echter: Als je omgekeerd vanuit de blank node naar de elementen wil die ernaar refereren zou een associatie inderdaad handig zijn, maar dat is dus een toevoeging om technische redenen en niet om semantische redenen. Semantisch klopt alles: de adresvoorstelling is een datatype en een attribuut van dat type is een onderdeel vd klasse, het adres staat bij het object waarvan het een kenmerk is.
- De oplossing die wordt voorgesteld hierboven (associatie met AdresseerbaarObject) is sowieso niet correct. De enige types objecten die in België adresseerbaar zijn (lees: een adres kunnen/mogen toegekend krijgen) zijn Gebouweenheden, Percelen, Standplaatsen en Ligplaatsen. Dit is bepaald door het Adrescomité en vastgelegd in de BestAdd-standaard.
- Conclusie: toevoegingen aan OSLO VOC's of AP's om technische redenen doen we niet. Het is aan het uiteindelijke implementatiemodel om deze toevoeging te doen indien nodig. Het platform waarop het VOC/AP geïmplementeerd wordt (RDF, SQL, XML... ) valt buiten het semantisch niveau waarop OSLO werkt (enkel conceptuele en applicatiemodellen, geen implementatiemodellen).

**Comment by rubcap** [comment]
Wordt gesloten o.b.v. de door Geert gegeven argumentatie hierboven. Voor de definitie van het 'adresseerbaar object' werd een apart issue #196 gemaakt.

Open gerust een nieuw issue bij verdere vragen of opmerkingen!
