### ISSUE TITLE
Organisatie; Resources van contactpoint geven error 404 op de website maar zijn wel bereikbaar via content negotiation 

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#139]
curl -L -H "Accept: application/rdf+xml" http://data.vlaanderen.be/id/organisatie/OVO003751
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="http://data.vlaanderen.be/doc/organisatie/OVO003751">
    <ns1:issued xmlns:ns1="http://purl.org/dc/terms/"
       rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-05-17T13:16:12Z</ns1:issued>
    <ns2:primaryTopic xmlns:ns2="http://xmlns.com/foaf/0.1/"
       rdf:resource="http://data.vlaanderen.be/id/organisatie/OVO003751"/>
  </rdf:Description>
  <ns3:Organization xmlns:ns3="http://www.w3.org/ns/org#"
     rdf:about="http://data.vlaanderen.be/id/organisatie/OVO003751">
    <ns4:uuid xmlns:ns4="http://mu.semte.ch/vocabularies/core/">OVO003751</ns4:uuid>
    <ns5:uuid xmlns:ns5="http://mu.semte.ch/vocabularies/core/"
       rdf:datatype="http://www.w3.org/2001/XMLSchema#string">OVO003751</ns5:uuid>
    <ns6:contactPoint xmlns:ns6="http://schema.org/"
       rdf:resource="http://data.vlaanderen.be/id/organisatie/OVO003751/contact/e7072d27-717e-53d1-658b-5a0ff6e34207"/>
    <ns7:contactPoint xmlns:ns7="http://schema.org/"
       rdf:resource="http://data.vlaanderen.be/id/organisatie/OVO003751/contact/fe1c3d37-e64b-3ab5-647e-13df1afd568a"/>
    <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Agent"/>
    <ns8:seeAlso xmlns:ns8="http://www.w3.org/2000/01/rdf-schema#"
       rdf:resource="https://wegwijs.vlaanderen.be/#/organisations/d19a7867-749a-dad6-4f30-351cc3a7fb66"/>
    <ns9:altLabel xmlns:ns9="http://www.w3.org/2004/02/skos/core#"
       rdf:datatype="http://www.w3.org/2001/XMLSchema#string">DIDM</ns9:altLabel>
    <ns10:prefLabel xmlns:ns10="http://www.w3.org/2004/02/skos/core#"
       rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Data- en informatiebeheer &amp; digitale maatschappij</ns10:prefLabel>
    <ns3:changedBy rdf:resource="http://data.vlaanderen.be/id/organisatie/OVO003751/oprichting"/>
    <ns3:classification rdf:resource="http://data.vlaanderen.be/id/concept/organisatieclassificatie/b5c586ed-f3dc-4273-b14a-2f458a5c07fa"/>
    <ns3:identifier rdf:datatype="http://www.w3.org/2001/XMLSchema#string">OVO003751</ns3:identifier>
    <ns11:orgStatus xmlns:ns11="http://www.w3.org/ns/regorg#"
       rdf:resource="http://data.vlaanderen.be/id/concept/organisatiestatus/actief"/>
  </ns3:Organization>
</rdf:RDF>

curl -L -H "Accept: application/rdf+xml" http://data.vlaanderen.be/id/organisatie/OVO003751/contact/e7072d27-717e-53d1-658b-5a0ff6e34207
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="http://data.vlaanderen.be/doc/organisatie/OVO003751/contact/e7072d27-717e-53d1-658b-5a0ff6e34207">
    <ns1:issued xmlns:ns1="http://purl.org/dc/terms/"
       rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-05-17T13:40:40Z</ns1:issued>
    <ns2:primaryTopic xmlns:ns2="http://xmlns.com/foaf/0.1/"
       rdf:resource="http://data.vlaanderen.be/id/organisatie/OVO003751/contact/e7072d27-717e-53d1-658b-5a0ff6e34207"/>
  </rdf:Description>
  <ns3:ContactPoint xmlns:ns3="http://schema.org/"
     rdf:about="http://data.vlaanderen.be/id/organisatie/OVO003751/contact/e7072d27-717e-53d1-658b-5a0ff6e34207">
    <ns4:uuid xmlns:ns4="http://mu.semte.ch/vocabularies/core/">e7072d27-717e-53d1-658b-5a0ff6e34207</ns4:uuid>
    <ns5:uuid xmlns:ns5="http://mu.semte.ch/vocabularies/core/"
       rdf:datatype="http://www.w3.org/2001/XMLSchema#string">e7072d27-717e-53d1-658b-5a0ff6e34207</ns5:uuid>
    <ns3:email rdf:datatype="http://www.w3.org/2001/XMLSchema#string">didm.omgeving@vlaanderen.be</ns3:email>
  </ns3:ContactPoint>
</rdf:RDF>

curl -L -H "Accept: application/rdf+xml" http://data.vlaanderen.be/id/organisatie/OVO003751/contact/fe1c3d37-e64b-3ab5-647e-13df1afd568a
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="http://data.vlaanderen.be/doc/organisatie/OVO003751/contact/fe1c3d37-e64b-3ab5-647e-13df1afd568a">
    <ns1:issued xmlns:ns1="http://purl.org/dc/terms/"
       rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-05-17T13:43:00Z</ns1:issued>
    <ns2:primaryTopic xmlns:ns2="http://xmlns.com/foaf/0.1/"
       rdf:resource="http://data.vlaanderen.be/id/organisatie/OVO003751/contact/fe1c3d37-e64b-3ab5-647e-13df1afd568a"/>
  </rdf:Description>
  <ns3:ContactPoint xmlns:ns3="http://schema.org/"
     rdf:about="http://data.vlaanderen.be/id/organisatie/OVO003751/contact/fe1c3d37-e64b-3ab5-647e-13df1afd568a">
    <ns4:uuid xmlns:ns4="http://mu.semte.ch/vocabularies/core/">fe1c3d37-e64b-3ab5-647e-13df1afd568a</ns4:uuid>
    <ns5:uuid xmlns:ns5="http://mu.semte.ch/vocabularies/core/"
       rdf:datatype="http://www.w3.org/2001/XMLSchema#string">fe1c3d37-e64b-3ab5-647e-13df1afd568a</ns5:uuid>
    <ns3:telephone rdf:datatype="http://www.w3.org/2001/XMLSchema#string">02 553 03 78</ns3:telephone>
  </ns3:ContactPoint>
</rdf:RDF>

**Comment by gezever** [comment]
![screenshot from 2018-05-17 15-44-23](https://user-images.githubusercontent.com/28095014/40181386-440024d8-59e9-11e8-8952-6d0d6e0f32ba.png)

**Comment by jensscheerlinck** [comment]
Dit was hoogstwaarschijnlijk een tijdelijk probleempje dat zich voordeed bij een migratie-oefening. Werkt opnieuw.
