### ISSUE TITLE
CPSV-AP:Event heeft onduidelijke semantiek

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Discussion#14]
Ondanks [onze feedback op JoinUp](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/event-actually-eventtype), gebruikt ISA de term `Event` om soorten events aan te duiden. Dit is problematisch omdat er geen duidelijke onderscheid is tussen een instantie ("de geboorte van Jan Peeters op 1 januari 2010") tegenover het type van event ("een geboorte van een kind").

In CPSV-AP wordt effectief het type bedoeld, dit blijkt uit de [discussie](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/event-actually-eventtype) en de [begeleidende documentatie](https://joinup.ec.europa.eu/asset/cpsv-ap/asset_release/core-public-service-vocabulary-application-profile-v20). De RDF documentatie, wat de echt formele bron is, impliceert echter het gebruik van instanties:

> This class represents an event that can be of any type that triggers, makes use of, or in some way is related to, a Public Service.

> This class represents a Business Event, which specialises Event. A Business Event is a specific situation or event in the lifecycle of a business that fulfils one or more needs or (legal) obligations of that business at this specific point in time. A Business Event requires a set of public services to be delivered and consumed in order for the associated business need(s) or obligation(s) to be fulfilled. Business Events are defined within the context of a particular Member State. In other words, a Business Event groups together a number of public services that need to be delivered for completing that particular event.

> The Life Event class represents an important event or situations in a citizen's life where public services may be required. Note the scope: an individual will encounter any number of 'events' in the general sense of the word. In the context of the CPSV-AP, the Life Event class only represents an event for which a Public Service is related. For example, a couple becoming engaged is not a CPSV-AP Life Event, getting married is, since only the latter has any relevance to public services.

Ook heeft de `Event` klasse een type, wat lijkt te overlappen met de gesuggereerde subtyperingen.

Enerzijds kunnen deze vage definities leiden naar verkeerd gebruik, anderzijds zal het makkelijkere adoptie hebben tegenover een zelf opgestelde term in landen buiten België.

Definiëren we onze eigen versie van `Event` of niet? en hoe gaan we om met het type ervan?

**Comment by dhaeneth** [comment]
Ik ijver voor een meertalige benadering waarbij we binnen OSLO een nederlandstalige variant hanteren.

CPSV-AP heeft de heel duidelijke doelstelling om te gaan met de catalogusfunctie - in die optiek specialiseren wij de inhoud (binnen OSLO) standaard (in de nederlandstalige specs) best nog eens naar de 'type'-betekenis. In een engelse terminologie ben ik wat weigerachtig om af te stappen van wat overeengekomen is binnen CPSV-AP working group qua naamgeving. Kunnen we niet zeggen 'OSLO:Dienstverlening:TypeGebeurtenis' sameAs ''CPSV-AP:Event'?

Als we gaan naar instanties denk ik dat we best een soortgelijke oefening maken voor een verwant profiel (wat men vandaag niet wil binnen Europa). Een soort OSLO:DienstverleningOpMaat... Een discussie om ook daar te voeren...

**Comment by DieterDePaepe** [comment]
Ik ben ook voorstander om `Event` te blijven gebruiken.

De keuze van oslo eigen termen te definiëren tegenover gewoon de termen over te nemen is een discussie voor de domeinmodel groep.

**Comment by jensscheerlinck** [comment]
In het finale OSLO model is dit opgenomen als een "PersoonsGebeurtenis" en een "BedrijfsGebeurtenis", beiden specialisaties van een "Gebeurtenis" die als entry point dienen voor een bepaalde Publieke Dienstverlening (bv. alle dienstverlening m.b.t. het starten van een eigen zaak, de geboorte van een kind...)
