### ISSUE TITLE
Mandaat: reden beëindiging toevoegen

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLO-Discussion#141]
* Context: het ontwerp-BVR legt de gemeente, het district of het openbaar centrum voor maatschappelijk welzijn de einddatum van het mandaat en de reden van beëindiging te publiceren binnen tien dagen na de einddatum van het mandaat. Nu is dit niet voorzien in het model.

* Voorstel: Toevoegen van het attribuut “redenVanBeëindiging” aan Rechtsgrond:beëindiging

**Comment by mvanbrab** [comment]
Zit er in; issue zal mogen gesloten worden na nieuwe publicatie.
