### ISSUE TITLE
Organisatie LOD; dochterondernemingen / onderlinge organisatorische samenhang. 

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#142]
In de LOD voorstelling van Organisatie zijn er geen onderlinge relaties tussen de verschillende organisaties. 
Nochthans kan je op de wegwijs pagina's wel zien wat de dochterorganisaties van een organisatie zijn. Zou het geen nuttige aanvulling zijn op de LOD dataset om ook hier relaties als dochteronderneming toe te voegen.

endpoint: http://data.vlaanderen.be/sparql
query: " SELECT Distinct * from <http://data.vlaanderen.be/id/dataset/wegwijs> WHERE {
  ?s a <http://www.w3.org/ns/org#Organization> ;
     ?p ?o .
  ?o a <http://www.w3.org/ns/org#Organization> .
 }"

**Comment by gezever** [comment]
Bij het kbo vind je deze informatie wel, welliswaar niet gekoppeld aan beleidsdomein.
endpoint: http://data.kbodata.be/#sparql
query: "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX oslo: <http://purl.org/oslo/ns/localgov#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT * WHERE {
bind (<http://data.kbodata.be/organisation/0316_380_841#id> as ?org)
    ?org 
        a rov:RegisteredOrganization ;
        oslo:companyStatus <http://data.kbodata.be/status/AC#id> ;
        <http://www.w3.org/ns/org#hasSite> ?site .
}"

**Comment by dhaeneth** [comment]
Zeker een nuttige aanvulling.
De relaties tussen organisaties onderling (of het nu gaat om hiërarchie of een andere relatie) zijn idd nog niet ontsloten via linked data. Dat staat dit jaar op de planning.

FYI : jouw voorbeeld van KBO gaat niet over relaties tussen organisaties onderling, maar over de relatie tussen een organisatie en haar vestigingen (semantisch een groot verschil). De KBO wordt hier eigenlijk 'misbruikt' om toch onze agentschappen zonder rechtspersoonlijkheid een 'identiteit' te geven (weliswaar als soort van 'administratieve vestiging').  De onmogelijkheid om op een semantisch correcte manier dergelijke zaken kwijt te kunnen in de KBO is net één van de bestaansredenen van het organisatieregister.

**Comment by gezever** [comment]
Ok, bedankt voor de reactie.

**Comment by jensscheerlinck** [comment]
Ik sluit deze issue aangezien geen impact op het semantisch model.
Verder op te nemen door @dhaeneth in context van uitrol organisatieregister LOD product.
