### ISSUE TITLE
Extra objecten: Boomspiegel en Luchtleiding

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#147]
Vraag van AWV

Vandaag wordt in de wegendatabank ook een inventaris van bomen bijgehouden.
Naast de objecten die nu reeds in het model aanwezig zijn worden ook nog twee extra objecten geïnventariseerd:

- Boomspiegel
- Luchtleiding

Deze kunnen respectievelijk als terreindeel en infrastructuur-element worden gecatalogeerd.

**Comment by JokeVanDeMaele2** [comment]
Wij kozen ervoor om boomspiegels onder te brengen volgens type onder

- Kruidachtigen (bvb begroeid met vaste planten)
- Houtachtigen (bvb haag)
- Grasachtigen (bvb grasrabatten)
- Onbegroeid Voorkomen (bij boomroosters of kale grond)

bij elk van deze objecten is dan een aanvinkveld 'is boomkader' om ook een 'lijst van alle boomspiegels' te kunnen exporteren.

**Comment by JokeVanDeMaele2** [comment]
Als extra voorzieningen voor bomen houden we bij (als kenmerk aan het object Boom)

- bevloeiing (te begrijpen: een permanent bevloeiingssyteem voor bomen die geen grondwater binnen bereik hebben)
- kroonverankering
- meegroeiverlichting
- niet- meegroeiende verlichting (bomen die jaarlijks van verlichting worden voorzien, kenmerk blijft dus behouden ook als de verlichting er niet in hangt op dat moment)

We kozen ervoor om tijdelijke irrigatie, beluchting en boompalen niet bij te houden, omdat die standaard bij quasi elke boom worden voorzien én omdat ze enkel bij de aanslagfase van belang zijn. 

- De nood om boompalen weg te halen wordt niet uit de inventaris gehaald, maar bij begeleidingssnoei meegenomen.
- De beluchtings- en irrigatiebuizen behoeven geen verdere taken.

**Comment by jensscheerlinck** [comment]
Besproken tijdens webcast op 26 september 2018
Voorstel van oplossing werd aanvaard:

Definitie “Boomspiegel”: “De boomspiegel is het stuk grond rondom de stam van een boom dat van boven toegankelijk is voor lucht en water”

Luchtleiding, Boomrooster, Boomspiegel, Boomplaat worden geïmplementeerd als attribuut bij “Boomvorm” in plaats van als afzonderlijke objecten.

Geïmplementeerd in commit: https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/c0400668b0be709bf67f73f53e0ab5f67c7958c1

Resultaat: https://data.vlaanderen.be/doc/applicatieprofiel/vegetatiecataloog/
