### ISSUE TITLE
Suggestie voor URIs "begin" en "einde" voor datatype Tijdsinterval

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#150]
Momenteel bestaat in OSLO Generiek een datatype Tijdsinterval (`http://purl.org/dc/terms/PeriodOfTime`)

De attributen van dit datatype (begin en einde) zijn gedefinieerd in de data.vlaanderen.be/ns/generiek namespace:

- `http://data.vlaanderen.be/ns/generiek#Tijdsinterval.begin`
- `http://data.vlaanderen.be/ns/generiek#Tijdsinterval.einde`

De ISA Core Criterion and Core Evidence Vocabulary definieert ook een Tijdsinterval, als volgt:
```turtle
#-- Class definition -->

<http://data.europa.eu/m8g/PeriodOfTime> a rdfs:Class ;
  rdfs:label "Period of time"@en ;
  rdfs:comment "An interval of time that is named or defined by its start and end times."@en .

#-- Properties definition -->

<http://data.europa.eu/m8g/startTime> a rdf:Property ;
  rdfs:label "start time"@en ;
  rdfs:comment "The date and time on which the period of time starts."@en ;
  rdfs:domain cv:PeriodOfTime .

<http://data.europa.eu/m8g/endTime> a rdf:Property ;
  rdfs:label "end time"@en ;
  rdfs:comment "The date and time on which the period of time finalizes."@en ;
  rdfs:domain cv:PeriodOfTime .
```

**Comment by GeertThijs** [comment]
Wordt in de VOC's die in de repo zitten nergens gebruikt vreemd genoeg. In andere VOC's wel? Waarbij het dan beter is om deze te gebruiken?

**Comment by GeertThijs** [comment]
TODO: uri-tags toe te voegen....

**Comment by GeertThijs** [comment]
DONE

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0
