### ISSUE TITLE
Hondenuitlaatplaats vs Hondenloopzone

### ISSUE THREAD

**Issue by JokeVanDeMaele2** [Informatievlaanderen/OSLO-Discussion#154]
OSLO Openbaar domein

Aanvulling in de terreindelen

Hondenloopzone: zonder leiband en wel opruimplicht (zie ook https://www.antwerpen.be/nl/overzicht/dieren/dierenwelzijn/hondenloopzones-tips-en-afspraken) + er is een afsluiting

Hondenuitlaatplaats: definitie nu = leiband verplicht en geen opruimplicht; komt overeen met https://www.natuurenbos.be/hondenzones + geen hekwerk

**Comment by jensscheerlinck** [comment]
Besproken tijdens webcast op 26 september 2018
Voorstel van oplossing werd aanvaard:

* Hondentoilet herdefiniëren: niet afgebakend, geen opruimplicht, wel leiband
* Hondenuitlaatplaats verwijderen als terreindeel: afgebakend, geen opruimplicht, wel leiband
* Hondenloopzone toevoegen als terreindeel: afgebakend, wel opruimplicht, geen leiband

Geïmplementeerd in commit: https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/c0400668b0be709bf67f73f53e0ab5f67c7958c1

Resultaat: https://data.vlaanderen.be/doc/applicatieprofiel/infrastructuurcataloog/
