### ISSUE TITLE
Blok (begraafplaats)

### ISSUE THREAD

**Issue by JokeVanDeMaele2** [Informatievlaanderen/OSLO-Discussion#155]
in Begraafplaats rij wordt melding gemaakt van Blok
"Beschrijving
Een rij is een verzameling graven van hetzelfde type. Een rij ligt typisch volledig binnen een bepaald blok."

in de taxonomie wordt geen Blok gedefinieerd
(in de stuurgroep wel, voor het daar gedefinieerde terreindeel gebruiken wij het synoniem Perk)

**Comment by jensscheerlinck** [comment]
Besproken tijdens webcast op 26 september 2018
Voorstel van oplossing werd aanvaard:

Toevoegen van terreindeel voor "blok" op basis van overleg 15/03.

Geïmplementeerd in commit: https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/c0400668b0be709bf67f73f53e0ab5f67c7958c1

Resultaat: https://data.vlaanderen.be/doc/applicatieprofiel/begraafplaats/
