### ISSUE TITLE
Vraag rond 'Adresvoorstelling.locatieaanduiding'

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#159]
_From @rubcap on June 29, 2018 14:15_

**Context:**
'Locatieaanduiding' komt als attribuut voor in het vocabularium Adres binnen het datatype 'Adresvoorstelling', en eveneens in het vocabularium Gebouw binnen het object 'Gebouweenheid'.

**Vraag:**
Moet 'locatieaanduiding' onder datatype 'Adresvoorstelling' niet van het datatype 'Locatieaanduiding' zijn en multipliciteit [0..*] hebben, om bv. de vleugel, trap, verdieping en deur van een gebouweenheid apart te kunnen opgeven? En is dan geen constraint nodig die ervoor zorgt dat je bv. 'deur' maar één keer kunt opgeven en niet meerdere keren?

_Copied from original issue: Informatievlaanderen/Data.Vlaanderen.be#119_

**Comment by jensscheerlinck** [comment]
_From @bertvannuffelen on July 2, 2018 9:14_

Ruben,

We moeten hier onderscheid maken tussen een data-uitwisselings afspraken en zulke detail constraints over een specifieke stroom van data. Ik pleit ervoor om afspraken zoals "slechts 1 keer een deur" niet op te nemen in het vocabularium/applicatieprofiel als de struktuur van het vocabularium dit niet toelaat om te specifiëren. 

Adresvoorstelling is een vlakke voorstelling van een adres. Als we daarin constraints willen gaan uitdrukken dan moeten we de vlakke struktuur aanpassen. En dat willen we denk ik niet. 

Trouwens als de feed komt van een adresregister dan kunnen we verwachten dat dit slechts 1 keer zal aanwezig zijn omwille van connectie met het gestructureerde Belgische adres.

**Comment by rubcap** [comment]
'Adresvoorstelling.locatieaanduiding' werd aangepast naar multipliciteit `[0..*] {ordered}`. Dit laat toe om bijvoorbeeld de vleugel-, trap-, verdieping- en deuraanduiding in de juiste volgorde in de Adresvoorstelling op te nemen. Vanwege de vlakke structuur van 'Adresvoorstelling' (enkel tekstvelden) dient het type aanduiding in het tekstveld te worden meegenomen, bv. `vleugel A` en `trap A`.

Dezelfde multipliciteit is van toepassing op 'Gebouweenheid.locatieAanduiding'. Door het datatype 'Locatieaanduiding' te gebruiken kunnen de aanduidingen en hun type op een gestructureerde manier worden opgenomen bij de gebouweenheid.
