### ISSUE TITLE
Opportuun om codelijsten 'geometriemethode' samen te voegen?

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#160]
_From @rubcap on June 29, 2018 13:11_

**Context:**
Er is een aparte codelijst voor geometriemethode, binnen de datatypes 'GeografischePositie' (vocabularium Adres) resp. '2DGebouwgeometrie' (vocabularium Gebouw). 

**Voorstel:**
Niet één codelijst voor puntgeometrieën en één voor 2Dgeometrieën, maar één generiekere (gedeelde) codelijst.

**Motivatie:**
Semantisch bestaat er tussen deze codelijsten voldoende overlap om deze samen te voegen?

_Copied from original issue: Informatievlaanderen/Data.Vlaanderen.be#118_

**Comment by jensscheerlinck** [comment]
_From @rubcap on June 29, 2018 13:12_

![codelijst_geometriemethode](https://user-images.githubusercontent.com/26146350/42094044-c382cf8a-7bae-11e8-921e-23c3e56586b4.png)

**Comment by jensscheerlinck** [comment]
_From @rubcap on June 29, 2018 15:40_

Op de werkgroep-Gebouwenregister van 12 juni was er weinig animo voor dit voorstel.
Als tegenargumenten werden aangehaald:
- Sommige codes uit de generieke codelijst, zoals 'ingemeten' of 'ingemetenGRB', zijn niet toepasbaar op adressen. Je zou al meteen een restrictie op het gebruik van de codelijst voor adresposities moeten zetten.
- Een 'ingeschetst' gebouw zegt nog altijd meer dan een gebouw 'aangeduid door beheerder'. Een positie duid je aan, een polygoon schets je.

**Comment by rubcap** [comment]
Voorstel niet weerhouden wegens argumentatie in https://github.com/Informatievlaanderen/OSLO-Discussion/issues/160#issuecomment-421339122.
