### ISSUE TITLE
Hernoem 'gebouwstatus' en 'gebouweenheidstatus' naar 'status'

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#162]
_From @rubcap on June 29, 2018 11:58_

**Motivatie:** 
uniformiteit met het vocabularium 'Adres', waarin ook een veld 'status' voorkomt bij 'Straatnaam' en 'Adres'.

_Copied from original issue: Informatievlaanderen/Data.Vlaanderen.be#116_

**Comment by rubcap** [comment]
Deze aanpassing zal doorgevoerd worden in een volgende update van het vocabularium en applicatieprofiel Gebouw.
