### ISSUE TITLE
Welke Events zijn relevant voor een organisatie?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Discussion#17]
Welke soorten Events moeten bijgehouden worden voor een organisatie?

CPOV: definieert enkel `FoundationEvent`.

**Comment by dhaeneth** [comment]
Sluiting (of vereffening), 'conceptie' (formele mogelijkheid tot oprichting)

**Comment by SuzieFavere** [comment]
"Oprichting", "statutenwijzigingen", "opheffing", "vereffening", "omvorming"van bv een feitelijke vereniging naar een vzw, "aansluitingen" van bv gemeenten bij een opdrachthoudende of dienstverlenende vereniging, "uittredingen"



Ik zet hieronder nog eens de info over feitelijke vereniging die kan omgevormd worden tot vzw:
Feitelijke vereniging of VZW?

Een feitelijke vereniging ontstaat van zodra twee of meer personen het idee ontwikkelen om gezamenlijk een ideëel doel te verwezenlijken. 
Een feitelijke vereniging kan beschouwd worden als het "clubje". 
Doordat de feitelijke vereniging geen juridische grond (geen rechtspersoonlijkheid) heeft, kan zij geen verbintenissen aangaan, geen eigendommen bezitten, geen schenkingen of legaten aanvaarden en zijn het de individuele leden die zich persoonlijk verbinden tot de verplichtingen van de vereniging. Als een vereniging, door de realisatie van haar maatschappelijk doel, aanzienlijke risico's neemt, of onroerende goederen wil verwerven of schenkingen en legaten wenst te aanvaarden, dan doet zij er goed aan om haar structuur van feitelijke vereniging om te vormen naar een vzw.

Omdat feitelijke verenigingen geen rechtspersoonlijkheid hebben worden ze niet geregistreerd.

**Comment by dhaeneth** [comment]
Goede feedback - dit gaat wel over de huidige visie van KBO op de materie. Ik ga er in de toekomst wel van uit dat we dit wel zullen kunnen registreren - zij spelen uiteindelijk wel een rol in publieke dienstverlening (hoewel ze geen rp hebben). Hoe gaan we bvb om met intercommunales zonder rp?

**Comment by dhaeneth** [comment]
Ik stel voor dat ik deze info meeneem in het uitwerken van use case voor de uiteindelijke spec

**Comment by jensscheerlinck** [comment]
Cf #27
