### ISSUE TITLE
Hoe omgaan met niet stemmende mandatarissen?

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#176]
_From @DieterDePaepe on January 2, 2018 16:3_

> In een aantal besturen doet het zich voor dat de mandataris toch aanwezig is maar dat hij niet stemt. Dit wordt dan ook zo opgenomen in de notulen. 

Deze vraag werd gesteld tijdens het webinar van het domein Besluit.

_Copied from original issue: Informatievlaanderen/Data.Vlaanderen.be#55_

**Comment by jensscheerlinck** [comment]
_From @DieterDePaepe on January 2, 2018 16:5_

Als een mandataris aanwezig is maar niet stemt, dan dient zijn stem meegeteld te worden bij de onthoudingen. Tijdens de webinar was hierover discussie, we stellen voor om dit apart nog verder uit te klaren.

De vraag is of iemand die blijft zitten tijdens de gemeenteraad en die niet wenst deel te nemen aan de stemming, meegeteld wordt als onthouding of op een andere manier geteld wordt.

**Comment by brechtvdv** [comment]
De gebruiksnota van "heeft onthouder" vermeldt dat als de mandataris weigert (en dus niet wenst deel te nemen) deze mandataris als onthouder wordt meegeteld.
Aangezien deze gebruiksnota een weerslag is van de werkgroepen stel ik voor om dit te behouden en dus het ticket ook te sluiten.
