### ISSUE TITLE
Typo aanschrijfvorm in generiek-basis

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#191]
**Model(len) waarop de issue van toepassing is:** 
generiek-basis

**Omschrijving van het probleem:** 
typo uri aanschrijfvorm: http://ww.w3.org/2006/vcard/ns#honorific-prefix
 

**Omschrijving van een mogelijke oplossing:**
De url is http://w3.org/2006/vcard/ns#honorific-prefix

**Comment by mvanbrab** [comment]
Volgens https://www.w3.org/TR/vcard-rdf/: uri = http://www.w3.org/2006/vcard/ns#honorific-prefix. Propageert ook in Inname Openbaar Domein, Toestemming in Notificatie (waarvan ik de .eap files alle zal aanpassen)

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/f79be3291c35e4d46f6941a0f803f057b0a8651a
