### ISSUE TITLE
gebruik van Plaats in verkeersbordendatabank

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#198]
**Model(len) waarop de issue van toepassing is:** 
https://test.data.vlaanderen.be/doc/applicatieprofiel/verkeersbordendatabank/

**Omschrijving van het probleem:** 
De notie generiek:Plaats wordt gebruikt om de locatie aan te duiden waar het verkeersbord zich bevindt.
Deze notie is echter niet geschikt hiervoor omdat het de intentie van deze klasse is de verzameling van 
plaatsnamen met hun geometriën (zoals "langs de schelde", "Gent", "de mollekensberg").
Ik denk dat de intentie hier is om de juist punt locatie van waar het verkeersbord zich bevindt aan te duiden. 

Indien het toch de intentie is om plaatsnamen te gebruiken dan is het best om een hiervoor een motivatie te schrijven. Met een gebruiksnota.

**Omschrijving van een mogelijke oplossing:**
Vervangen van de klasse Plaats door het datatype generiek:Geometrie of generiek:GeografischePositie

**Comment by brechtvdv** [comment]
Plaats is vervangen door generiek:Geometrie wegens geen noodzaak om plaatsbeschrijving bij te houden op Opstelling.
