### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Discussion#23]
We hebben een aantal concrete use cases nodig om het model aan te toetsen.

**Comment by DieterDePaepe** [comment]
Enkele use cases vermeld tijdens de eerste publieke werkgroep:

> Bij het aanvragen van een identiteitskaart  is de federale overheid de authoriteit, maar de dienst kost in alle 308 gemeenten anders.

> De premie voor het verwijderen van graffiti is een lokale bevoegdheid waar er Vlaamse premies voor bestaan.

Vanuit welk perspectief wordt dit aangeboden en zullen dit dan andere producten zijn afhankelijk van wie dit uitreikt?

**Comment by nvdk** [comment]
Een extra use case:
een public services die een kost heeft afhankelijk van aantal parameters (bv prijs bepaald door sociaal statuut).

**Comment by dhaeneth** [comment]
Vraag is of een catalogus (CPSV-AP) de plaats is om alle contextfactoren uit te tekenen (cfr issue rond Kost)?

**Comment by dhaeneth** [comment]
Use case:

Mensen weten vaak niet wat hun rechten/plichten zijn. Generieke use case van deze oefening is de condities creëren opdat alle actoren (burgers, ondernemingen) inzicht kunnen krijgen in die rechten/plichten en algemene modaliteiten (zonder daarom te instantiëren of te personaliseren).

**Comment by dhaeneth** [comment]
Use case : 

Het aantal aanbieders en het aanbod van PD is vandaag een chaos. Vanuit de idee 'één overheid' en 'de overheid begrijpt u' is het noodzakelijk orde te brengen in die chaos, ttz centraal identificeren, benoemen en registreren PD en deze onderling relateren.

**Comment by KatrienDS** [comment]
@DieterDePaepe : Een aantal lokale besturen heeft een premie voor het verwijderen van graffiti, er bestaan  geen Vlaamse premies voor

**Comment by KatrienDS** [comment]
De uitpas is een lokaal voorbeeld waarbij de prijs verschilt volgens inkomen.

https://stad.gent/cultuur-sport-vrije-tijd/uitgaan-en-organiseren/uitpas
https://www.uitinoostende.be/uitpas#PRIJZEN
https://www.uitinmechelen.be/uitpas

**Comment by bertvannuffelen** [comment]
@dhaeneth: orde binnen de chaos. Ik denk dat deze usecase een hele belangrijke is en dat die een meta status heeft. Namelijk hoe kan het OSLO2 werk ertoe bijdragen dan de chaos geordend wordt zonder dat iedereen in een keurslijf moet komen. Wat zijn de stappen zodaning dat waar overeenkomsten zijn, deze versterkt worden en waar er verschillen zijn, deze behouden kunnen blijven.

Ik denk dat hier een OSLO2 ondersteuning van de gedistribueerde (ver)(be)werking van de data een cruciaal element speelt. B.v. in stad Gent willen ze mensen ouder dan 50 aan het zwemmen krijgen en dus is er een veteranenprijs voor iedereen boven 50, terwijl bij andere steden er staat gepensioneerden (een niet zo leeftijdsgebonden categorie). Het systeem moet toelaten om dit verschil te behouden maar anderzijds ook toe te laten dat de categorie "gepensioneerde" overal waar ie gebruikt wordt een gelijke betekenis krijgt.

**Comment by dhaeneth** [comment]
@bertvannuffelen Klopt. Het enige dat ik daar realistisch zie, is dat een partij (Informatie Vlaanderen?) aan centraal gecoördineerd doch decentraal beheer van codelijsten gaat doen en ism. de betrokkenen het beheer/de creatie op te nemen van een inhoudelijke domeinbeschrijving (in vaktermen een 'ontologie'). Voor jouw concreet voorbeeld zal dat bvb. kunnen betekenen dat we (i) starten met de semantische inventaris v/h woord 'gepensioneerde', de verschillende invullingen (elk nog steeds met eigen semantiek) relateren aan een granulaire lijst (met leeftijden in deze) om al een meerwaarde in interoperabiliteit te creëren en (ii) de discussie aangaan om de semantiek overal gelijk te trekken (langetermijntraject).

En dat voor alles dat we tegenkomen :-).
Ik denk er eens over na of we dit in de schoot van OSLO² kunnen doen (want het is domeinoverschrijdend zoals je zelf aangeeft en gebeurt dus best holistisch).

**Comment by jensscheerlinck** [comment]
Hier werd vertrokken vanuit de use cases zoals gedefinieerd door ISA voor het CPSV-AP model (waar dit een quasi 1-op-1 vertaling van is). 

Intussen werd het model ook reeds getoetst aan de praktijk in de context van een aantal trajecten: dienstverleningsregister, subsidieregister...
