### ISSUE TITLE
Vermijden van duplicaten in DCAT-AP-VL metadata

### ISSUE THREAD

**Issue by stijngoedertier** [Informatievlaanderen/OSLO-Discussion#236]
**Model(len) waarop de issue van toepassing is:** DCAT-AP-VL

**Omschrijving van het probleem:** Om metadata te kunnen uitwisselen tussen dataportalen (bijvoorbeeld tussen het portaal van stad Antwerpen en het Vlaamse Open Dataportaal) kunnen we best uitgaan van een unieke, stabiele identificator voor elk dataset record. Dit maakt het eenvoudiger om duplicaten te vermijden. De Europese [DCAT-AP](https://joinup.ec.europa.eu/release/dcat-ap/12)  specificatie legt echter GEEN verplichting op aan het gebruik van een identificator. Het zou goed zijn mocht DCAT-AP-VL dit wél doen. 

**Omschrijving van een mogelijke oplossing:** De eenvoudigste oplossing lijkt mij de dataset URI verplicht te maken. In de praktijk geven de meeste dataportalen in Vlaanderen reeds een unieke dataset URI mee, enkel deze JSON-LD feed uit [arcgis.com](http://portaal-stadantwerpen.opendata.arcgis.com/data.jsonld) van Stad Antwerpen is een uitzondering. In deze feed zijn de dcat:Datasest resources zogenaamde "[blank nodes](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node)" dus zonder URI (hoewel er in deze feed wel voor elke dataset een dct:identifier eigenschap is met HTTP URI). Door de dataset URI verplicht te maken, kunnen dataportalen eenvoudiger afdwingen dat er voor elke dataset slechts  één beschrijving in de metadata voorkomt.

**Comment by bertvannuffelen** [comment]
De volgende aanbeveling is gemaakt: https://joinup.ec.europa.eu/release/dcat-ap-how-use-identifiers-datasets-and-distributions.
Een andere relevant track van discussie: https://github.com/w3c/dxwg/issues/771.

**Comment by bertvannuffelen** [comment]
opgenomen in finale versie als usage note
