### ISSUE TITLE
[MOBILITEIT VOC] Innamezone.beheerder is enige beheerder met afwijkende uri

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLO-Discussion#246]
**Model(len) waarop de issue van toepassing is:** 
Vocabularium OSLO-Mobiliteit

**Omschrijving van het probleem:** 
Bijna alle properties "beheerder" mappen op dezelfde uri: https://data.vlaanderen.be/ns/mobiliteit#beheerder.
Uitzondering: deze in klasse "Innamezone", die mapt op https://data.vlaanderen.be/ns/mobiliteit#Innamezone.beheerder.

Is deze uitzondering nodig?

**Omschrijving van een mogelijke oplossing:**
Alle properties "beheerder" op dezelfde manier definiëren.

**Comment by brechtvdv** [comment]
Deze uitzondering was niet de bedoeling.
Gezien de klasse "Innamezone" toch niet meer bestaat (wegens vervanging naar algemene "Zone") en alle beheerders https://data.vlaanderen.be/ns/mobiliteit#beheerder gebruiken, kan dit ticket gesloten worden.
