### ISSUE TITLE
Moet Procedure in het model? Of is procedure een specifiek type van Zaak?

### ISSUE THREAD

**Issue by ArneDeProft** [Informatievlaanderen/OSLO-Discussion#249]

**Comment by GeertThijs** [comment]
Ter info: het [AP Dienstencataloog](https://data.vlaanderen.be/doc/applicatieprofiel/dienstencataloog) heeft ook een klasse Procedure.

**Comment by ArneDeProft** [comment]
Een dienstverlening, die een bepaalde procedure volgt (set van regels, stappen, richtlijnen) is een specifiek soort zaak. Dit is reeds een aantal workshops geleden uitgeklaar
