### ISSUE TITLE
Is een Dossier altijd gelinkt aan Procedurestappen?

### ISSUE THREAD

**Issue by ArneDeProft** [Informatievlaanderen/OSLO-Discussion#251]

**Comment by ArneDeProft** [comment]
Een dossier is altijd gelinkt aan een zaak, en een zaak is altijd gelinkt aan procedurestappen.

**Comment by gezever** [comment]
Het is belangrijk dat we een felxibel model hebben. Soms beschikken we bij archivering niet over de informatie tijdens welke procedurestap een document is toegevoegd. Daarom is het handig om de verzameling documenten (prov:Collection) als neerslag van een (abstracte) eenheid werk (dbo:UnitOfWork) te zien. De neerslag van een volledige Zaak (dbo:Case (rdfs:subClassOf  dbo:UnitOfWork)) noemen we dan Dossier (rdfs:subClassOf prov:Collection).
Voor de verzameling documenten (prov:Collection) die de neerslag is van een volledige Procedurestap moeten we nog een naam bedenken.
Een andere verzamelingen van documenten in het kader van archief is een Serie.
