### ISSUE TITLE
Kan documentonderdeel vervangen worden door link van Document naar Document?

### ISSUE THREAD

**Issue by ArneDeProft** [Informatievlaanderen/OSLO-Discussion#252]

**Comment by GeertThijs** [comment]
Zoals vermeld in #256 is in OSLO-Generiek Document & DocumentOnderdeel gemodelleerd. Inderdaad apart. Het model in woorden:

- Een Documentonderdeel wordt niet als een op zichzelf staand Document beschouwd.
- Een DocumentOnderdeel heeft kenmerken die een Document niet kan hebben, zoals een paragraafnummer (attributen type - bv paragraaf - en nummer).
- Een DocumentOnderdeel kan uit DocumentOnderdelen bestaan, er loopt dus een associatie van DocumentOnderdeel naar zichzelf.
- Maar een Document kan niet uit Documenten bestaan.

**Comment by gezever** [comment]
Een Document en een Documentonderdeel binnen dossier zijn beiden een specialisatie van een prov:Entity en worden gebruikt en gegenereerd tijdens een prov:Activity.

De relatie tussen Document en Documentonderdeel is prov:hadMember (domain prov:Collection, range prov:Entity , waarbij prov:Collection een specialisatie van prov:Entity is). 
Dit betekent:
- dat een Document (prov:Entity) een prov:Collection wordt eens er members zijn.
- dat een Document in principe uit Documenten kan bestaan.

Dossier is een specialisatie van prov:Collection (ttz. een Dossier is een verzameling documenten als neerslag van een zaak, dbo:Case)
Documentonderdelen bevinden zich op het niveau van een bitstream. Een document, eenheid van een te staven, te bewijzen, of te documenteren iets, kan uit onderdelen bestaan, foto, geluid, tekst, ... 
De nood om verschillende paragrafen te onderscheiden binnen één bitstream opgelossen door deze als documentonderdeel te typeren is een lapmiddel en werkt niet bij een implementatie zoals een digitaal archief, waarbij bitstreams op een item gemetadateerd worden in een vlakke structuur. 
Een betere aanpak is ervoor zorgen dat een document als eenheid van een te staven, te bewijzen, of te documenteren iets correct gedefiniëerd is. 
bv. Als een bepaalde persoon een rekeningnummer moet toevoegen binnen een procedure, en dit heeft een betekenis, is het zaak om dit appart te documenteren op niveau van een Document. Op die manier kan dit op de meest granulaire manier, bv. in een digitaal archief op Item-niveau, worden gemetadateerd en is dit een bewijs dat er een rekeningnummer is toegevoegd tijdens deze procedure.

**Comment by ArneDeProft** [comment]
Relatie tussen document en documentonderdeel - is uitgeklaard in de vorige werkgroep en wordt behouden volgens de voorbeelden die momenteel in OSLO worden opgenomen

Issue was er gekomen door een verwarring door de gebruikte voorbeelden in vorige workshops
