### ISSUE TITLE
Is er nood aan versiebeheer in het model?

### ISSUE THREAD

**Issue by ArneDeProft** [Informatievlaanderen/OSLO-Discussion#254]

**Comment by GeertThijs** [comment]
OSLO-modellen beschrijven de huidige toestand ve domein, niet de toestanden uit het verleden en/of hoe die elkaar hebben opgevolgd. Meer uitleg daarover in de [OSLO-modelleringsregels](https://github.com/Informatievlaanderen/OSLO-handleiding/tree/master/Modelleringsregels), zie §3.1.5 in de pdf. Enige uitzondering is wanneer de historiek semantisch betekenis heeft, bv een Bestuursorgaan zelf heeft geen Mandaten, enkel een Bestuursorgaan tijdens zijn bestuursperiode heeft Mandaten. Historiek is wel relevant voor het implementatiemodel dat uiteindelijk vh applicatiemodel zal worden afgeleid, de uitwerking ervan kan verschillen al naargelang het implementatieplatform. Om aan te geven op welke elementen dan welke historiek nodig is maakten we een [UML-profiel voor historiek](https://github.com/Informatievlaanderen/OSLO-handleiding/blob/master/Modelleringsregels/OSLO-HistoriekProfiel.xml). Hoe je het gebruikt wordt [ook uitgelegd](https://github.com/Informatievlaanderen/OSLO-handleiding/blob/master/Modelleringsregels/Historiek.pdf).

**Comment by ArneDeProft** [comment]
Het betreft niet versiebeheer van het model maar de data die nodig is voor
	- Versiebeheer van het dossier
	- Versiebeheer van de onderliggende documenten
	- …
Te bekijken of hier noden zijn voor bepaalde attributen. Wordt bepaald in volgende workshop.
