### ISSUE TITLE
Dossier: Hergebruik Document en DocumentOnderdeel uit OSLO-Generiek?

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO-Discussion#256]
**Model(len) waarop de issue van toepassing is:**
Dossier. 

**Omschrijving van het probleem:**
Ter info: Document en DocumentOnderdeel werden toegevoegd aan [OSLO-Generiek](https://data.vlaanderen.be/doc/applicatieprofiel/generiek-basis) nadat ze ihkv [OSLO-Besluit](https://data.vlaanderen.be/doc/applicatieprofiel/besluit-publicatie) geïntroduceerd werden. 

**Omschrijving van een mogelijke oplossing:**
Hergebruik in OSLO-Dossier?

**Comment by HenkV** [comment]
Volgens OSLO is een document: 
Een origineel werk in de brede zin (een verslag, een opname, een boek...).
Deze definitie is mijns inziens te ruim.

Volgens Van Dale is een document: 
Van Dale omschrijft een document o.a. als: ieder (geschreven of gedrukt) bewijsstuk

Een document zou men kunnen zien als een specialisatie van een informatieobject.
Mogelijke definitie volgens de site van Nationaal archief Nederland (https://www.nationaalarchief.nl/archiveren/kennisbank/informatieobject) --> Informatie:object: een op zichzelf staand geheel van gegevens met een eigen identiteit. Een informatieobject is een verzameling aan elkaar gerelateerde gegevens die als eenheid wordt behandeld.

**Comment by gezever** [comment]
Het Document in oslo-generiek is een http://xmlns.com/foaf/0.1/Document.
Dit heeft als definitie: "The Document class represents those things which are, broadly conceived, 'documents'."
De belangrijkste reden om deze definitie niet over te nemen is omdat deze definitie circulair en daarom nietszeggend is. 
Wij zullen het document van dossier definiëren als subclass van prov:Entity

**Comment by GeertThijs** [comment]
De definitie in FOAF is inderdaad waardeloos. De WG Besluit & Mandaat paste daarom de definitie aan in het AP als volgt: 

- Een origineel werk in de brede zin (een verslag, een opname, een boek...).

Waarna we de klasse Document naar OSLO-Generiek overbrachten voor algemeen gebruik, overigens samen met Documentonderdeel dat ermee geassocieerd is (ook ingevoerd door de WG Besluit & Mandaat).
Er zijn nu 3 mogelijkheden:

- Er wordt in OSLO-Dossier een eigen klasse Document gecreëerd. Die klasse blijft in die namespace en is dus enkel bedoeld voor gebruik in de context van Dossiers.

- Er wordt door OSLO-Dossier een nieuwe klasse Document gemaakt en we nemen deze over in OSLO-Generiek. (Gekoppeld aan Documentonderdeel dan wel.)

- OSLO-Dossier gebruikt alsnog de huidige klasse Dossier uit OSLO-Generiek maar we passen de definitie aan.

De eerste oplossing is makkelijkst maar is niet erg bevordelijk voor de semantische interoperabiliteit. Besluit & Mandaat kan dan nl niet praten met Dossier als het over documenten gaat.
Oplossingen 2 of 3 hebben mijn voorkeur, maar dan zal overleg met de WG Besluit en Mandaat nodig zijn @brechtvdv om te zien of zij de eventuele impact daarvan aanvaarden (de uri EN/OF de definitie verandert immers).

**Comment by gezever** [comment]
Besluit kan een subclass zijn van Document binnen dossier. 

Wat de definities binnen een applicatieprofiel zijn lijkt me secundair. Ontologisch commitment volgt uit de ontologie. 
Wanneer je zou besluiten om de ontologische definitie van Document te wijzigen binnen generiek heeft dit impact op alle datasets die momenteel gebruik maken van foaf:Document. Al die datasets moeten bijgevolg door een OWL reasoner, zoals  Pellet, worden getoetst tegen deze aangepaste ontologie.

**Comment by ArneDeProft** [comment]
Gezien deze definitie al afgestemd is in een OSLO werkgroep is ons voorstel om de klasse over te nemen uit OSLO generiek, maar wel een voorstel te doen om de definitie daarvan aan te passen.
We willen/kunnen die niet eenzijdig aanpassen vanuit OSLO Dossier en stellen voor om als follow-up een overlegmoment/workshop te organiseren, specifiek rond de definitie van dit object, die de werkgroep dossier overstijgt, die open is voor iedereen, en waar minsten de werkgroepleden van mandaat en besluit expliciet worden voor uitgenodigd.
