### ISSUE TITLE
applicatieprofiel DCAT-AP-VL, onduidelijkheid in de beschrijving

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#266]
Bij de beschrijving van het applicatieprofiel voor DCAT-AP-VL (https://data.vlaanderen.be/doc/applicatieprofiel/DCAT-AP-VL/) staat er een zin die ik niet helemaal begrijp en die mogelijk problematisch is.
"Om conform te zijn met dit applicatieprofiel, geldt voor een implementatie dat ze: MAG NIET terminologie van andere gecontroleerde vocabularia gebruiken dan diegene die gedefinieerd wordt in dit applicatieprofiel."

**Comment by koenedaele** [comment]
Dat kan ik lezen als: er mogen enkel properties gebruikt worden uit dit profiel. Het zou me logischer lijken dat je de properties en classes uit het profiel gebruikt, maar eventueel ook kan aanvullen met eigen properties voor dingen die niet voorzien zijn. Zodat je bv. zelf de feed kan gebruiken voor interne doeleinden door toevoeging van 1 of 2 velden.

**Comment by bertvannuffelen** [comment]
We zullen dit verduidelijken.

**Comment by bertvannuffelen** [comment]
Dit is verduidelijkt in de de finale tekst.
