### ISSUE TITLE
DCAT-AP-VL: maar 1 beschrijving?

### ISSUE THREAD

**Issue by koenedaele** [Informatievlaanderen/OSLO-Discussion#267]
**Model(len) waarop de issue van toepassing is:**

DCAT-AP-VL 

**Omschrijving van het probleem:**

Een Dataset heeft een description en een title met kardinaliteit 1. De description en title is een TaalString. Normaal kan je dus een description en een title per taal hebben. De kardinaliteit 1 lijkt dit onmogelijk te maken?

**Omschrijving van een mogelijke oplossing:**

Kardinaliteit lijkt me 1 per taal te moeten zijn.

**Comment by koenedaele** [comment]
Net gemerkt dat dit bij DatsetCatalogus wel 1....n is.

**Comment by bertvannuffelen** [comment]
Dat is een goede opmerking. Ik denk dat dit misschien zelfs een generieke opmerking is. Want in andere OSLO modellen hebben we dit voor.

De juiste oplossing weet ik nog niet, maar minstens een usage note is van toepassing.

**Comment by bertvannuffelen** [comment]
opgelost door expliciet op te nemen in gebruiksnota
