### ISSUE TITLE
Voorbeelden VeranderingsMoment

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Discussion#27]
We hebben naast oprichting en stopzetting andere voorbeelden nodig van een `VeranderingsMoment`.

Bvb: fusie van meerdere bedrijven, splitsing van een bedrijf.

**Comment by jensscheerlinck** [comment]
Momenteel zitten volgende veranderingsmomenten vervat in het model:

- Oprichting
- Splitsing
- Fusie
- Vervanging
- Stopzetting

Cf. https://data.vlaanderen.be/ns/organisatie
