### ISSUE TITLE
dcat:accessURL is a rdfs:Resource not a string

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#270]
**Omschrijving van het probleem:** 
In de kandidaatstandaard staat dat een toegangsURL (dcat:accessURL) een string is, maar het moet een rdfs:Resource, dus een URI zijn

**Omschrijving van een mogelijke oplossing:**
Range aanpassen van toegangURL.

**Comment by akuckartz** [comment]
For DCAT 2 see:
https://w3c.github.io/dxwg/dcat/#Property:distribution_access_url

For DCAT 1 see:
https://www.w3.org/TR/vocab-dcat/#Property:distribution_accessurl

**Comment by bertvannuffelen** [comment]
aangepast en opgenomen
