### ISSUE TITLE
verkeersborden > hergebruik externe termen

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#275]
**Model(len) waarop de issue van toepassing is:** 
https://data.vlaanderen.be/doc/applicatieprofiel/verkeersborden/

**Omschrijving van het probleem:** 

Het hergebruiken van externe termen moet met zorg gebeuren. Hier worden een aantal termen herbruikt uit dbpedia. Echter deze hebben een range en domein welke verschillend is met de range en domein in het applicatieprofiel.

**Omschrijving van een mogelijke oplossing:**

Dit is geen alleenstaand geval voor dit applicatieprofiel, maar hier is de incompatibiliteit misschien wel groot.

**Comment by brechtvdv** [comment]
Breedte, hoogte, diameter en kleur worden zelf gedefinieerd ipv overgenomen van dbpedia ontology
