### ISSUE TITLE
verkeersborden > overname van externe termen uit openbaar domein

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#276]
**Model(len) waarop de issue van toepassing is:** 
https://data.vlaanderen.be/doc/applicatieprofiel/verkeersborden/

**Omschrijving van het probleem:** 
Er worden heel wat termen overgenomen uit openbaardomein. Echter deze klassen zoals Afsluiting e.d. hebben geen bijkomende definities, nog eigenschappen in dit applicatieprofiel.
Wat is de doelstelling om deze mee op te nemen?  

**Omschrijving van een mogelijke oplossing:**
Als het enkel een opsomming is van de verschillende mogelijkheden die vandaag bestaan, dan is het beter om die niet mee op te nemen. 

Indien het de doelstelling is om alle beperkingen en constraints van het applicatieprofiel openbaar-domein infrastructuur elementen over te nemen dan moet je overschakelijk op de nieuwe toolchain en hierbij de juiste dependency aanduiden.

**Comment by brechtvdv** [comment]
De bedoeling is om te kunnen valideren waaraan een retroreflecterend verkeersbord kan opgehangen worden. Dit is dus meer dan een opsomming.

De constraints van het applicatieprofiel openbaar-domein mogen niet overgenomen worden, gezien dit enkel bedoeld is ter verwijzing naar zo'n inventaris van infrastructuurelementen.
