### ISSUE TITLE
waarom string en niet codelijst

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#277]
**Model(len) waarop de issue van toepassing is:** 
https://data.vlaanderen.be/ns/mobiliteit#conformStandaard

**Omschrijving van het probleem:** 
hier wordt een string verwacht als range. Misschien interessanter een codelijst?

**Omschrijving van een mogelijke oplossing:**
In dit geval is dat een verwijzing naar een afspraken kader. Met een string weet je niets over dat kader. Het is dan aan de mens om te weten waar dat kader te vinden is.

**Comment by brechtvdv** [comment]
Ik pas dit aan naar "Code". Ook voor attribuut fabricagevoorschrift van SteunRetroreflecterendVerkeersbord zal ik de range hiernaar aanpassen.
