### ISSUE TITLE
verkeersborden > incorrecte URI assignment

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#278]
**Model(len) waarop de issue van toepassing is:** 
https://data.vlaanderen.be/doc/applicatieprofiel/verkeersborden/#Opstelling%3Ahoort%20bij

**Omschrijving van het probleem:** 
verwijst naar locn:geometry

**Omschrijving van een mogelijke oplossing:**
dat lijkt me een typo

**Comment by brechtvdv** [comment]
Eigen URI gemaakt: https://data.vlaanderen.be/ns/mobiliteit#hoortBij
