### ISSUE TITLE
[Perceel] Incorrect gebruik van de term 'kadastraal planperceel'

### ISSUE THREAD

**Issue by JokeDW** [Informatievlaanderen/OSLO-Discussion#289]
**Model(len) waarop de issue van toepassing is:** 
Perceel - draft html

**Omschrijving van het probleem:** 
Entiteit 'Kadastraal Patrimoniumperceel' - 'Gebruik': De termen 'Kadastraal planperceel' en 'Kadastraal patrimoniumperceel' worden door elkaar gebruikt.

**Omschrijving van een mogelijke oplossing:**
De correcte term is hier 'kadastraal patrimoniumperceel'.

**Comment by KevinHaleydt** [comment]
Dit issue is opgelost in de gepubliceerde versie van OSLO Perceel op data.vlaanderen.be.
