### ISSUE TITLE
[Perceel] Eigenschap ID ontbreekt voor kadastraal planperceel

### ISSUE THREAD

**Issue by JokeDW** [Informatievlaanderen/OSLO-Discussion#290]
**Model(len) waarop de issue van toepassing is:** 
Perceel - draft HTML + model

**Omschrijving van het probleem:** 
Het kadastraal planperceel heeft ook een eigenschap 'ID'. Deze wordt wel beschreven onder 'Gebruik', maar staat niet vermeld in de lijst van eigenschappen noch in het model.

**Comment by KevinHaleydt** [comment]
Hi Joke,

We hebben inderdaad geen eigenschap 'identificator' toegevoegd aan de entiteit Kadastraal Planperceel. Dit komt doordat het een specialisatie is van Ruimtelijke eenheid en bijgevolg dit attribuut overerft. Het Kadastraal Patrimoniumperceel is echter geen specialisatie van Ruimtelijke eenheid waardoor we wel expliciet de identificator hebben toegevoegd.

Kevin
