### ISSUE TITLE
URI's van OTL ontbreken in mapping tabel

### ISSUE THREAD

**Issue by dimi-schepers** [Informatievlaanderen/OSLO-Discussion#296]
**Model(len) waarop de issue van toepassing is:** 
OSLO Openbaar Domein

**Omschrijving van het probleem:** 
De URI's van AWV/OTL ontbreken in de [mapping tabel](https://test.data.vlaanderen.be/cms/openbaardomein/AWV_mapping.html).

**Omschrijving van een mogelijke oplossing:**
De URI's van AWV/OTL toevoegen aan de mapping tabel.

**Comment by dimi-schepers** [comment]
In de [excel-file](https://github.com/Informatievlaanderen/Data.Vlaanderen.be/blob/test/site-skeleton/cms/openbaardomein/MappingPublicatie_v0.02.xlsx) zijn alle URI's wel aanwezig. Het is dus slechts een kwestie van de HTML-pagina te updaten.

**Comment by deefbas** [comment]
FYI, heb gemerkt dat de OD URIs in de [excel-file](https://github.com/Informatievlaanderen/Data.Vlaanderen.be/blob/test/site-skeleton/cms/openbaardomein/MappingPublicatie_v0.02.xlsx) uitkomen op een 404.
