### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#behandelt domain en range zijn niet correct

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#312]
**Model(len) waarop de issue van toepassing is:** 
oslo:Dossier

**Omschrijving van het probleem:** 
https://data.vlaanderen.be/ns/dossier#behandelt
Definitie: Een zaak behandelt een object.
Domein: http://www.w3.org/ns/prov#Entity
Bereik: http://dbpedia.org/ontology/Case

Domain Entity behandelt hier bereik Case.

**Omschrijving van een mogelijke oplossing:**
Als een zaak een object behandelt, is
Domain: http://dbpedia.org/ontology/Case
en
Range: rdfs:Resource of owl:Thing

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
