### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#beschrijft domain en range zijn niet correct

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#313]
**Model(len) waarop de issue van toepassing is:** 
oslo:Dossier

**Omschrijving van het probleem:** 
Definitie: Een stuk beschrijft een object.
Domein: https://data.vlaanderen.be/ns/dossier#Stuk
Bereik: http://www.w3.org/ns/prov#Entity
=> Stuk beschrijft Entity, tewijl Stuk ook een Activity kan beschrijven. 
Activity en Entity zijn disjoint.
Er dient dus een algemener bereik gedefinieerd te worden.

**Omschrijving van een mogelijke oplossing:**
Als een stuk een object beschrijft, is
Domein: https://data.vlaanderen.be/ns/dossier#Stuk
en
Bereik: rdfs:Resource of owl:Thing

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
