### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#collectie.bestaatUit Domein en Bereik zijn niet correct.

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#314]
**Model(len) waarop de issue van toepassing is:** 
oslo:Dossier
**Omschrijving van het probleem:** 
Domein: http://www.w3.org/ns/prov#Entity
Bereik: http://www.w3.org/ns/prov#Entity
Definitie: Een collectie bestaat uit entiteiten.
Specialisatie van: http://www.w3.org/ns/prov#hadMember

Hier zegt domain, range en specialisatie van: een Entiteit bestaat uit Entiteiten, wat op zich juist is aangezien Collection een subclass van Entity is en een Entity een Collection wordt door het gebruik van de property omdat prov:hadMember prov:Collection als domein heeft, maar het is een beetje verwarrend en niet ieder systeem of mens maakt onmiddelijk die inferentie.
**Omschrijving van een mogelijke oplossing:**
Domein: http://www.w3.org/ns/prov#Collection
Bereik: http://www.w3.org/ns/prov#Entity

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
