### ISSUE TITLE
 https://data.vlaanderen.be/ns/dossier#einddatum en https://data.vlaanderen.be/ns/dossier#startdatum: domein en definitie zijn niet correct.

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#315]
**Model(len) waarop de issue van toepassing is:** 
oslo:Dossier

**Omschrijving van het probleem:** 

Definitie: De startdatum van de entiteit.
en
Definitie: De einddatum van de entiteit.

Domein: http://www.w3.org/ns/prov#Entity

Specialisatie van: http://www.w3.org/ns/prov#startedAtTime
en
Specialisatie van: http://www.w3.org/ns/prov#endedAtTime

Het Domain van prov:endedAtTime en prov:startedAtTime is prov:Activity. 
Echter: prov:Entity en prov:Activity zijn disjoint.

Een stuk (Entity) heeft geen begin- en eindtijdstip. Een activiteit heeft dat wel.

**Omschrijving van een mogelijke oplossing:**
Definitie: De startdatum van de activiteit.
en
Definitie: De einddatum van de activiteit.

Domein: http://www.w3.org/ns/prov#Activity

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
