### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#isNeerslagVan is twee keer gedefinieerd, met een verschillend bereik.

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#316]
**Model(len) waarop de issue van toepassing is:** 
oslo:Dossier
**Omschrijving van het probleem:** 

Bereik | http://dbpedia.org/ontology/UnitOfWork
en
Bereik | http://dbpedia.org/ontology/Case

Iedere dbo:Case is een dbo:UnitOfWork, maar niet omgekeerd.

**Omschrijving van een mogelijke oplossing:**
Als je een onderscheid wil maken op property niveau tussen beiden kan je twee properties maken. 
bv.: https://data.vlaanderen.be/ns/dossier#isNeerslagVan en https://data.vlaanderen.be/ns/dossier#isNeerslagVanZaak.
Dit laat echter nog steeds toe om een Collection als  https://data.vlaanderen.be/ns/dossier#isNeerslagVan een Zaak te formuleren.
Indie je het eenvoudig wil houden, hou je enkel  https://data.vlaanderen.be/ns/dossier#isNeerslagVan met range  http://dbpedia.org/ontology/UnitOfWork over.

**Comment by gezever** [comment]
https://data.vlaanderen.be/ns/dossier#isNeerslagVan lijkt verdwenen uit het vocabularium

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
