### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#vindtPlaatsTijdens is twee keer gedefinieerd. Eén keer met het juiste domein en bereik en één keer met het foute.

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#317]
**Model(len) waarop de issue van toepassing is:** 
oslo:Dossier
**Omschrijving van het probleem:** 
Definitie | Een activiteit vindt plaats tijdens een eenheid van werk.
Eén van de twee heeft echter:
Domein | https://data.vlaanderen.be/ns/dossier#Procedurestap
Bereik | http://www.w3.org/ns/prov#Activity
Wat Procedurestap heeft plaats tijdens Activiteit betekent.

**Omschrijving van een mogelijke oplossing:**
De https://data.vlaanderen.be/ns/dossier#vindtPlaatsTijdens met 
Domein | https://data.vlaanderen.be/ns/dossier#Procedurestap
en
Bereik | http://www.w3.org/ns/prov#Activity
verwijderen.

**Comment by dimi-schepers** [comment]
Opgelost in [versie dd. 2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
