### ISSUE TITLE
 http://data.europa.eu/m8g/Participation bestaat niet.

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#318]
**Model(len) waarop de issue van toepassing is:** 
oslo:Dossier 
**Omschrijving van het probleem:** 
Er wordt binnen de Core Public Service Vocabulary (AP) (http://data.europa.eu/m8g/cpsvap rdf:type owl:Ontology) verwezen naar http://data.europa.eu/m8g/Participation als rdfs:isDefinedBy http://data.europa.eu/m8g/cpov, het Core Public Organisation Vocabulary. De klasse wordt dus niet gedefiniëerd binnen cpsvap.

Het statement dat deze klasse binnen http://data.europa.eu/m8g/cpov is gedefinieerd klopt niet.
maw. We gebruiken dingen waarvan we de aard niet kennen.

https://github.com/SEMICeu/CPOV/blob/master/releases/1.00/Core%20Public%20Organisation%20Vocabulary_v1.0.0.ttl
en
https://joinup.ec.europa.eu/solution/e-government-core-vocabularies/core-public-organisation-vocabulary

**Omschrijving van een mogelijke oplossing:**
Er bestaan binnen de provenance ontologie, waarop het grootste deel van oslo:Dossier is gebaseerd, meerdere qualificatie-klassen en -properties die een hele reeks van use-cases uitdrukkingen mogelijk maken.
Ik laat weten welke ik voor specifieke gevallen gebruik.

**Comment by gezever** [comment]
Zie ook https://github.com/Informatievlaanderen/OSLO-Discussion/issues/297

**Comment by brechtvdv** [comment]
Binnen het AP inname-openbaar-domein (https://data.vlaanderen.be/doc/applicatieprofiel/inname-openbaar-domein) maken we gebruik van rol-specialisatie: https://data.vlaanderen.be/doc/applicatieprofiel/inname-openbaar-domein/#Organisatie%20%28in%20rol%29%3Ais%20rolspecialisatie%20van. (Deze moet nog toegevoegd worden aan het vocabularium). 
Deze volgt dezelfde redenering als bij Tijdsspecialisatie: https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan

Deze bouwt ook voort op PROV-O.

**Comment by dimi-schepers** [comment]
Ik stel voor om te aligneren met SEMIC. Zie https://github.com/SEMICeu/Core-Person-Vocabulary/issues/6

Ik zie momenteel enkel de figuur en nog niet de RDF, maar ik denk dat zij voor Role zich baseren op https://www.w3.org/ns/org#Role. Het domein van de property role is echter wel owl:unionOf (org:Membership org:Post) terwijl zij playsRole op Agent definiëren. Dus nog te bekijken.

**Comment by gezever** [comment]
Ik stel voor om binnen een model dat voornamelijk op provenance gebaseerd is, de uitdrukkingsmogelijkheden van provenance uit te putten voor je nog eens een andere ontologie erbij haalt. Aangezien bij OSLO geen reasoning op data als validatiestap tov het model gebeurt, lijkt dat me de meest veilige optie. Ik weet dat Provenance goed in elkaar zit, laat ons zelf zo weinig mogelijk bricoleren aub.

**Comment by gezever** [comment]
Hierbij onze implementatie van het dossiermodel, gealinieerd op beslissingsaangelegenheid voor de dossiers van de digitale bouwaanvraag. 
![overzicht bouwaanvraag zaak en dossier](https://user-images.githubusercontent.com/28095014/79338788-28506c00-7f28-11ea-9782-103a7895b14d.png)

**Comment by gezever** [comment]
Zie ook https://data.dba-ontwikkel.omgeving.vlaanderen.be/

**Comment by dimi-schepers** [comment]
Opgelost in [versie dd. 2021-04-22](https://data.vlaanderen.be/doc/applicatieprofiel/dossier/kandidaatstandaard/2021-04-22).
