### ISSUE TITLE
Kardinaliteit activiteit/procedurestap -  optioneel ipv verplichting maken

### ISSUE THREAD

**Issue by ArneDeProft** [Informatievlaanderen/OSLO-Discussion#329]
**Model(len) waarop de issue van toepassing is:** 
OSLO:dossier
**Omschrijving van het probleem:** 
Momenteel moet een activiteit ontstaan uit één en minimum één procedurestap. Sommige kleine activiteiten (bv. ontvangen van een mail tijdens een vergunningsaanvraag 1e aanleg), kunnen niet worden gelinkt aan één specifieke procedurestap. 
**Omschrijving van een mogelijke oplossing:**
De kardinaliteit "activiteit --> procedurestap" van "1" aanpassen naar "0-1". En de kardinaliteit "procedurestap --> zaak" van "1-\*" naar "0-\*" aanpassen.

**Comment by gezever** [comment]
Ipv de kardinaliteit van "activiteit --> procedurestap" aan te passen.
De relatie verleggen naar de abstracte Unit of work.

**Comment by gezever** [comment]
Ipv de kardinaliteit van "activiteit --> procedurestap" aan te passen.
De relatie verleggen naar de abstracte Unit of work is een andere optie.

**Comment by dimi-schepers** [comment]
Het is wel vreemd dat Activiteit dan wat "zweeft", zonder relatie naar de Zaak.

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/applicatieprofiel/dossier/kandidaatstandaard/2021-04-22) via {Activiteit vindtPlaatsTijdens EenheidVanWerk/Zaak}.
