### ISSUE TITLE
Attribuut informatieclassificate

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#330]
**Model(len) waarop de issue van toepassing is:** 
oslo:Dossier

**Omschrijving van het probleem:** 
In het applicatieprofiel is de kardinaliteit van property informatieclassificate 1, ook op een volledig dossier.
Ik heb daarmee een aantal problemen. 
Ten eerste begrijp ik het verwachte gedrag, dat volgt uit een attribuut informatieclassificate op een dossier, niet helemaal. Het lijkt alsof deze property daar is gezet met een heel specifieke implementatie in het achterhoofd.

Bij onze achief-implementatie wordt een instance van de klasse Dossier vertegenwoordigt door een node, zonder werkelijke bitstreams, waaraan enkel een aantal metadata-velden met linken naar samenstellende delen zijn gekoppeld. 
Waarom zou in deze implementatie een veld informatieclassificate moeten worden toegevoegd? Volgens mij bevindt de gevoelige informatie zich in de bitstreams, stukken en stukonderdelen, niet 
op het niveau van volledige dossiers.

Bij een rdf implementatie is dit al helemaal vreemd. Daar ligt de informatieclassificatie eigenlijk op het niveau van iedere individuele triple.

**Comment by michieldk** [comment]
Ik begrijp de opmerking dat dit een implementatie-problematiek is, aangezien de insteek was dat je zowel voor het hele dossier, als voor onderliggende stukken afzonderlijk moet kunnen aanduiden welke informatieclassificatie van toepassing is. Dit lijkt sterk op structuren bijvoorbeeld bij een DMS waarbij een folder hebt waarop je rechten kunt toekennen en dat die dan doorvloeien naar de onderliggende documenten, waar je dan wel weer kan gaan specifiëren.

Echter, in de werkgroep is besproken dat het steek houd om effectief ook te kunnen zeggen dat "een dossier" een bepaalde gevoeligheid heeft. Dit hoeft dan niet noodzakelijk (maar kan wel, dit is dan applicatielogica op basis van business rules) door te stromen naar stukken (of omgekeerd).

Wel is er geen probleem om de kardinaliteit aan te passen. Klopt het dat daarmee het probleem/de vraag grotendeels opgelost is?

**Comment by gezever** [comment]
Indien informatieclassificate optioneel is, is het opgelost Michiel, inderdaad.

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/applicatieprofiel/dossier/kandidaatstandaard/2021-04-22).
