### ISSUE TITLE
foaf:Person is met hoofdletter

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#333]
**Meerdere ontologies, waaronder adres en gebouw** 

**Omschrijving van het probleem:** 
De klasse http://xmlns.com/foaf/0.1/Person wordt met lower case geschreven.
vb.
<https://data.vlaanderen.be/ns/gebouw> a owl:Ontology ;
    dcterms:contributor [ a foaf:person ]

**Omschrijving van een mogelijke oplossing:**
upper case

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
