### ISSUE TITLE
geen range voor  schorsingOpmerking in ap bedrijventerrein

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Discussion#337]
**Model(len) waarop de issue van toepassing is:** 
applicatieprofiel bedrijventerrein

**Omschrijving van het probleem:** 
geen range voor schorsingOpmerking 

**Omschrijving van een mogelijke oplossing:**
range toevoegen

**Comment by mvanbrab** [comment]
De voorgestelde oplossing/aanpassing is vanaf nu zichtbaar in de specificaties:
* https://otl-test.data.vlaanderen.be/doc/vocabularium/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard
* https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/bedrijventerrein/tijdens-aanpassingen-kandidaat-standaard

**Comment by bertvannuffelen** [comment]
opgenomen in specificatie
