### ISSUE TITLE
Creatiedatum heeft cardinaliteit 1 voor stuk en stukonderdeel

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#373]
**Oslo Dossier applicatieprofiel** 

**Vaak weten we niet wanneer iets gecreëerd is, maar weten we wel wanneer iets ingediend is of wanneer we iets publiceren.** 

**Omschrijving van een mogelijke oplossing:**
Creatiedatum weg
Superproperty http://purl.org/dc/terms/date op cardinaliteit 1, waardoor we de keuze hebben tussen de subproperties http://purl.org/dc/terms/issued, http://purl.org/dc/terms/dateSubmitted, http://purl.org/dc/terms/created, ...

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/applicatieprofiel/dossier/kandidaatstandaard/2021-04-22).
