### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#Procedurestap.startdatum 

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#374]
_Issues in deze repository dienen inhoudelijke en semantische issues met betrekking tot de verschillende OSLO domeinmodellen aan te kaarten. Om technische (broken links, verkeerde mapping van termen op URI's...) of editoriale (typo's, fouten in de HTML weergave...) problemen aan te kaarten verwijzen we naar de [Data.Vlaanderen.be repository](https://github.com/Informatievlaanderen/Data.Vlaanderen.be/issues)._

**Model(len) waarop de issue van toepassing is: Oslo Dossier en OSLO Besluitvorming** 

**Omschrijving van het probleem:** 
Procedurestap.startdatum heeft https://data.vlaanderen.be/ns/dossier#Procedurestap als domain, http://www.w3.org/2001/XMLSchema#date als range en is een subproperty van http://www.w3.org/ns/prov#startedAtTime.
Mogelijk is hier een dubbel probleem. Ten eerste is de range van http://www.w3.org/ns/prov#startedAtTime een http://www.w3.org/2001/XMLSchema#dateTime  ipv. een http://www.w3.org/2001/XMLSchema#date en ten tweede is het domain van http://www.w3.org/ns/prov#startedAtTime een http://www.w3.org/ns/prov#Activity.
https://data.vlaanderen.be/ns/dossier#Procedurestap is subclass van http://dbpedia.org/ontology/UnitOfWork, waar expliciet vermeld staat: 'It is different from Activity'.

**Omschrijving van een mogelijke oplossing:**

Wanneer je een startdatum wil op een Procedurestap, laat dan het subclassen van http://www.w3.org/ns/prov#startedAtTime

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
