### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#Activiteit.startdatum

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#375]
**Model(len) waarop de issue van toepassing is: OSLO Dossier en Oslo Besluitvorming** 

**Omschrijving van het probleem:** 
https://data.vlaanderen.be/ns/dossier#Activiteit.startdatum is subproperty van prov:startedAtTime, maar de ranges van de properties verschillen.
**Omschrijving van een mogelijke oplossing:**
Waarom is de property https://data.vlaanderen.be/ns/dossier#Activiteit.startdatum nodig?  prov:startedAtTime is toch ok? Domain van beide properties is prov:Activity

**Comment by dimi-schepers** [comment]
Opgelost in versie [2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
