### ISSUE TITLE
Auteur is een prov:Agent die niet voorkomt in het applicatieprofiel

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#377]
**Model(len) waarop de issue van toepassing is:OSLO Besluitvorming** 

**Omschrijving van het probleem:** 
In het applicatieprofiel van Besluitvorming heeft een Stuk een auteur. Die auteur is een prov:Agent. Echter, in de UML van het  applicatieprofiel komen enkel dcterm:Agent voor en prov:Association als subclass van dcterms:Agent. 
**Omschrijving van een mogelijke oplossing:**

**Comment by dimi-schepers** [comment]
In [OSLO Besluitvorming](https://data.vlaanderen.be/doc/applicatieprofiel/besluitvorming/erkendestandaard/2021-02-04), heeft Stuk een auteur met range dct:Agent. In [OSLO Dossier](https://data.vlaanderen.be/doc/applicatieprofiel/dossier/kandidaatstandaard/2021-04-22), heeft Stuk een auteur met range prov:Agent. In die eerste is daarom opgenomen in de specificatie dat er binnen dat AP uitgegaan mag worden van de equivalentie tussen dc:Agent en prov:Agent, zoals ook aangegeven in de [mapping van het W3C](https://www.w3.org/TR/2013/NOTE-prov-dc-20130430/).
