### ISSUE TITLE
Besluitvorming: https://data.vlaanderen.be/ns/dossier#isNeerslagVan lijkt verdwenen uit Dossier

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#387]
**Model(len) waarop de issue van toepassing is:** 
Besluitvorming 
Dossier
**Omschrijving van het probleem:** 
https://data.vlaanderen.be/ns/dossier#isNeerslagVan wordt gebruikt in AP beluitvorming met range https://data.vlaanderen.be/doc/applicatieprofiel/besluitvorming/#Besluitvormingsaangelegenheid en domain Dossier en ProcedurestapNeerslag, wij gebruiken het met range dbo:Case en range Procedurestap , maar het lijkt verdwenen uit het vocabularium onder https://data.vlaanderen.be/ns/dossier#
Nochthans zit het in de versie van het vocabularium dat Arne me op 2/9/2019 per mail heeft bezorgd en waartegen wij ontwikkeld hebben. 

<https://data.vlaanderen.be/ns/dossier#isNeerslagVan> a owl:ObjectProperty;
  rdfs:label "is neerslag van"@nl;
  rdfs:comment "Een collectie is een neerslag van een eenheid van werk."@nl;
  rdfs:domain prov:Collection;
  rdfs:isDefinedBy <https://data.vlaanderen.be/ns/dossier>;
  rdfs:range <http://dbpedia.org/ontology/UnitOfWork>,
    <http://dbpedia.org/ontology/Case> .

**Omschrijving van een mogelijke oplossing:**
Ik weet niet waarom dat gewijzigd is, naar aanleiding van welke github issue of wanneer, maar graag terug de abstracte klassen als domain en range aub

**Comment by dimi-schepers** [comment]
Deze zijn gedisambigueerd geworden in twee properties. In het uitgebreide vocabularium van Dossier, vind je ze beide terug: zie https://test.data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2020-06-01#Collectie.isNeerslagVan en https://test.data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2020-06-01#Dossier.isNeerslagVan.

Gerelateerde .ttl: https://github.com/Informatievlaanderen/OSLO-Generated/blob/test/doc/vocabularium/dossier/kandidaatstandaard/2020-06-01/voc/dossier-voc.ttl

**Comment by gezever** [comment]
Gezien de identieke domain en range was de  uri-wijziging naar https://data.vlaanderen.be/ns/dossier#Collectie.isNeerslagVan niet nodig.
Graag terug  https://data.vlaanderen.be/ns/dossier#isNeerslagVan aub.

**Comment by gezever** [comment]
Noem mij ouderwets en conventioneel, maar mijn properties beginnen met minuskel.

**Comment by dimi-schepers** [comment]
Opgelost in de [versie dd. 2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
