### ISSUE TITLE
Besluitvorming: https://data.vlaanderen.be/ns/dossier#Dossier is  rdfs:subClassOf prov:Collection

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#388]
**Model(len) waarop de issue van toepassing is:** 
Besluitvorming
Dossier
**Omschrijving van het probleem:** 
Een dossier is een prov:Collection, dit is verdwenen uit het vocabularium. http://data.vlaanderen.be/ns/dossier#Dossier.bestaatUit is trouwens  rdfs:subPropertyOf  prov:hadMember, dit is niet verdwenen uit het vocabularium.
Geen idee waarom dit verdwenen is.
**Omschrijving van een mogelijke oplossing:**
<http://data.vlaanderen.be/ns/dossier#Dossier> a owl:Class ;
    rdfs:label "Dossier"@nl ;
    rdfs:comment "Samenhangend geheel van stukken die betrekking hebben op een bepaalde zaak. "@nl ;
    rdfs:isDefinedBy <http://data.vlaanderen.be/ns/dossier#> ;
    rdfs:subClassOf prov:Collection .

**Comment by dimi-schepers** [comment]
Opgelost in de [versie dd. 2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
