### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#beschrijft toevoegen aan vocabularium

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#395]
**Model(len) waarop de issue van toepassing is:** 
OSLO:Dossier
**Omschrijving van het probleem:** 
https://data.vlaanderen.be/ns/dossier#beschrijft komt voor in het applicatieprofiel https://test.data.vlaanderen.be/doc/applicatieprofiel/dossier/#Stuk%3Abeschrijft maar niet in het vocabularium (https://test.data.vlaanderen.be/ns/dossier#beschrijft)
**Omschrijving van een mogelijke oplossing:**
https://.data.vlaanderen.be/ns/dossier#beschrijft toevoegen aan vocabularium

dossier:beschrijft  rdf:type     rdf:Property ;
        rdfs:label          "beschrijft"@nl ;
        rdfs:isDefinedBy    <https://.data.vlaanderen.be/ns/dossier#> ;
        rdfs:range          rdfs:Resource ;
        rdfs:domain           "dossier:Stuk"  .

**Comment by dimi-schepers** [comment]
Opgelost in de [versie dd. 2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
