### ISSUE TITLE
https://data.vlaanderen.be/ns/dossier#behandelt toevoegen aan vocabularium

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Discussion#396]
Model(len) waarop de issue van toepassing is:
OSLO:Dossier
Omschrijving van het probleem:
https://data.vlaanderen.be/ns/dossier#behandelt komt voor in het applicatieprofiel https://test.data.vlaanderen.be/doc/applicatieprofiel/dossier/#Stuk%3Abehandelt maar niet in het vocabularium (https://test.data.vlaanderen.be/ns/dossier#behandelt)
Omschrijving van een mogelijke oplossing:
https://.data.vlaanderen.be/ns/dossier#behandelt toevoegen aan vocabularium

dossier:behandelt rdf:type rdf:Property ;
rdfs:label "behandelt"@nl ;
rdfs:isDefinedBy https://.data.vlaanderen.be/ns/dossier# ;
rdfs:range rdfs:Resource ;
rdfs:domain "dbo:Case" .

**Comment by dimi-schepers** [comment]
Opgelost in de [versie dd. 2021-04-22](https://data.vlaanderen.be/doc/vocabularium/dossier/kandidaatstandaard/2021-04-22).
