### ISSUE TITLE
Is "Gezin" geschikt als concept?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Discussion#4]
`Gezin` is momenteel aanwezig in het model. Kan dit concept correct gedefinieerd worden? Is een gezin meer dan haar leden? Hou verhoudt `IsGezinsLid` zich tegenover `GehuisvestDoor`, `EchtgenootOfPartnerVan` of `StamtAfVan`?

**Comment by DieterDePaepe** [comment]
Wat zijn use cases voor `Gezin`? Zijn er juridische implicaties?

**Comment by jdevreese** [comment]
- Ik heb ergens gelezen dat het bij zorgwonen kan voorkomen dat 2 verschillende gezinnen op hetzelfde adres wonen.
- Maakt een kind dat afwisselend bij beide gescheiden ouders woont, deel uit van meerdere gezinnen?
  - Wat is de waarde van `GehuisvestDoor` in zo'n geval?
- Wat met adoptie? Ik denk niet dat je in dat geval `StamtAfVan` kan gebruiken.

**Comment by bartrosseau** [comment]
Gezin is heel flou.
Inderdaad nagaan wanneer dit impact heeft. Onderscheid tussen aantal personen op adres gedomicilieerd (maar wat met samenwonende studenten bvb?), familiale of emotionele band (tweede is moeilijk administratief te bepalen), etc...
Misschien wel nagaan i nwelke reglementen het concept 'gezin' voor dat specifiek product kan afgeleid worden van andere elementen (huwelijk, samenwoonst, afstamming, domicilie, ...)

**Comment by KatrienLeire** [comment]
De relaties uit IT141 (echtgenoot, nicht, grootvader,...) naar het object gezin doen verwijzen zal vreemde resultaten geven, bvb bij neef  aangezien de relatie zich altijd tot de referentiepersoon verhoudt. Er bestaat niet echt een relatieaanduiding in gezin behalve gezinshoofd en gezinslid.  Je kan een gezin ook niet echt benoemen, enkel een id geven... Wat is de lifecycle van een gezin?

**Comment by jensscheerlinck** [comment]
De huidige definitie is momenteel ruim opgevat, om toe te laten dat in bepaalde business contexten specialisaties van dit begrip worden voorzien.

> Samenwerkingsvorm die een herkenbare sociale eenheid vormt (bv tgv huwelijk), met al dan niet verwante personen die duurzame banden hebben en elkaar onderling steun en verzorging verlenen.
