### ISSUE TITLE
Kunnen we publieke dienstverlening opsplitsen ifv. de doelgroep (onderneming) ea. ?

### ISSUE THREAD

**Issue by dhaeneth** [Informatievlaanderen/OSLO-Discussion#41]
Er is nood om de publieke dienstverlening voor ondernemingen te clusteren naar grootte onderneming, vestiging (adres), thematiek (bouwen, leefmilieu, ...). Kan dit vandaag in dit model?

**Comment by jensscheerlinck** [comment]
Enkel grootte onderneming is volgens mij niet mogelijk.

Vestigingsadres -> toepassingsgebied (http://purl.org/dc/terms/spatial)
Thematiek -> sector (http://data.europa.eu/m8g/sector), volgt NACE codelijst

Grootte onderneming kan eventueel alsnog opgevangen worden met de eigenschap "trefwoord"
