### ISSUE TITLE
Kunnen richtlijnen ook door machines geïnterpreteerd worden?

### ISSUE THREAD

**Issue by dhaeneth** [Informatievlaanderen/OSLO-Discussion#42]
Is het mogelijk om dienstverlening te gaan verfijnen door een machine ifv. de richtlijnen die erop van toepassing zijn?

**Comment by jensscheerlinck** [comment]
Is dit inmiddels uitgeklaard of moet hier nog een actie voor aangemaakt worden in OSLO²?

**Comment by DieterDePaepe** [comment]
Nog verder te bekijken. Precieze context van de vraag is me ook niet duidelijk, een voorbeeld zou handig zijn.

**Comment by jensscheerlinck** [comment]
We gaan dit bekijken bij de implementatie van de Vlaamse Codex als Linked Open Data.
