### ISSUE TITLE
Verwijzing naar Gezin vanuit Gezinsrelatie + analogie met Huwelijk

### ISSUE THREAD

**Issue by jdevreese** [Informatievlaanderen/OSLO-Discussion#49]
Een Persoon kan in sommige gevallen misschien deel uitmaken van één of meerdere Gezinnen?
Als er een Gezinsrelatie uitgedrukt wordt met betrekking tot die Persoon, lijk het mij nuttig om aan te kunnen geven in context van welk Gezin dat is.

Hetzelfde zou je kunnen doen voor een Huwelijksrelatie. Die relatie zou kunnen verwijzen naar een Huwelijk-klasse waar je dan extra informatie aan zou kunnen koppelen (een begin- en einddatum, een akte, de instantie die het huwelijk erkent, ...)

**Comment by DieterDePaepe** [comment]
Het huidige model laat dergelijke uitbreidingen in de toekomst toe, maar is nog niet in de huidige versie opgenomen.

**Comment by GeertThijs** [comment]
- Momenteel is inderdaad voorzien dat een Persoon tot meerdere gezinnen kan behoren. Echter kan steeds afgeleid worden tot welk gezin de persoon betrokken in de relatie behoort. Maw: geen relatie nodig.
- Wat de klasse voor Huwelijk betreft: die is alvast aanwezig. Welke data verder nog moet toegevoegd worden (alvast zeker begin- en einddatum) is nog te bepalen (voor een volgende iteratie en/of AP Persoon RR).

**Comment by jensscheerlinck** [comment]
Op basis van input @GeertThijs sluit ik deze issue
