### ISSUE TITLE
Use cases nodig

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Discussion#5]
Er zijn momenteel nog geen use cases voor de werkgroep persoon om het model aan te toetsen buiten het algemene "interoperabiliteit is nodig".

**Comment by DieterDePaepe** [comment]
Use cases vermeld tijdens de 1e publieke op 12 januari:

> Een Fransman, met domicilie in Frankrijk, maar met buitenverblijf hier in België die een K.I.-aanslag moet toegezonden worden. Deze zit in Bis Register van KSZ tenzij de persoon al in België zou geresideerd hebben in het verleden.

> Een kind met gescheiden ouders verblijft bij beide ouders. Toch heeft het maar 1 hoofd verblijfplaats.

**Comment by DieterDePaepe** [comment]
Use case uit #6:

In het huidige model voorstel is wettelijk samenwonen mee opgenomen in de burgerlijke staat. In België is dit echter geen officiële burgerlijke staat (dit telt als "ongehuwd"). De twee zijn echter verschillende begrippen. Hoe past dit in het model?

**Comment by jensscheerlinck** [comment]
De use cases zijn terug te vinden in de inleidende teksten van de vocabularia en applicatieprofielen op:
https://data.vlaanderen.be/ns/
