### ISSUE TITLE
Jurdische gebied 

### ISSUE THREAD

**Issue by peterneesCS** [Informatievlaanderen/OSLO-Discussion#51]
Jurisdictie heeft ene attribuut van type Geografische naam. Concreet representeert dit attribuut een verwijzing naar een staat of deelstaten. Zoals ik het nu begrijp, is Geografische naam de veralgemening van Gemeente, Staat en Deelstaat.
Is het misschien niet nuttig om een begrip als Juridisch gebied te introduceren, die staat en deelstaat veralgemeent. Je zou dan volgende hierarchie krijgen:
Geografische naam is of een gemeente, of een Juridisch gebied. Jurdische gebied is of een Staat, of een deelstaat.
De plaats van een Jurisdictie is dan een Juridisch gebied.

**Comment by jensscheerlinck** [comment]
Issue besproken door OSLO² werkgroep op 25/09:

Het datatype Geografische naam kan gebruikt worden om generiek eender welke plaats een textueel label mee te geven. Om het gebruik ervan duidelijk te maken in de context van Jurisdictie, zal extra documentatie worden toegevoegd aan de specificatie van het model aan de hand van een gebruiksnotitie.
