### ISSUE TITLE
Consent

### ISSUE THREAD

**Issue by peterneesCS** [Informatievlaanderen/OSLO-Discussion#54]
Ik vraag me af of er geen begrip van Consent in Olso moet zitten, gezien het belang van GDPR.

**Comment by jensscheerlinck** [comment]
Hier wordt momenteel aan gewerkt. Een eerste versie voor publieke review volgt nog dit jaar.

**Comment by jensscheerlinck** [comment]
Een eerste, publiek afgestemde versie, van een vocabularium rond "Toestemming" (= consent) is terug te vinden via:

https://data.vlaanderen.be/ns/toestemming

De bedoeling is dat deze in het najaar wordt voorgelegd als "kandidaat-standaard".
