### ISSUE TITLE
Officiële naam >< leesbare/verstaanbare naam

### ISSUE THREAD

**Issue by KatrienDS** [Informatievlaanderen/OSLO-Discussion#56]
In de definities bij OSLO dienstverlening wordt bij de naam van de dienstverlening, bewijs, output, ... vermeld officiële naam. Als hiermee de naam bedoeld wordt zoals dit opgenomen is in de regelgeving dan zal je hier vaak zeer technische namen tegenkomen die niet echt begrijpbaar zijn voor een doorsnee burger. Als je de link naar de officiële naam wil behouden,  kan het een oplossing zijn om een bijkomend veld te voorzien waarin je toelaat dat er een eerder beschrijvende titel meegegeven wordt. vb. In de use case rommelmarkt die al uitgewerkt is, zou de officiële naam van de dienstverlening moeten zijn:  toelating tot het organiseren van occasionele verkopen zonder commercieel doel.

**Comment by jensscheerlinck** [comment]
Issue besproken door OSLO² werkgroep op 25/09:

Voor het meegeven van een alternatieve naam voor een Publieke Dienstverlening kan gebruik gemaakt worden van het attribuut "trefwoord". Hiermee kan bijvoorbeeld een verkorte of alternatieve naam meegegeven worden voor de Publieke Dienstverlening. 

Voor output en bewijs wordt voorgesteld om deze informatie te capteren onder "beschrijving".

**Comment by jensscheerlinck** [comment]
Aan de klasse Publieke Dienstverlening zal de eigenschap "alternatieve naam" worden toegevoegd.
(https://www.w3.org/2009/08/skos-reference/skos.html#altLabel)

**Comment by jensscheerlinck** [comment]
Heeft geen impact op het vocabularium, aangezien een externe term (uit SKOS) wordt toegevoegd aan het Applicatieprofiel. Op te nemen door @GeertThijs in volgende iteratie van het AP.

**Comment by GeertThijs** [comment]
Is het voorstel om "trefwoord" hiervoor te gebruiken dan niet ok?

**Comment by GeertThijs** [comment]
TODO: extra attribuut, optioneel, skos altlabel.

**Comment by GeertThijs** [comment]
DONE

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0
