### ISSUE TITLE
Eenmanszaken

### ISSUE THREAD

**Issue by peterneesCS** [Informatievlaanderen/OSLO-Discussion#57]
Voor eenmanszaken is een associatie nodig tussen een het Persoondomein en het Organisatiedomein. Momenteel is er enkel een zeer abstracte, en dus betekenisloze link vanuit Agent naar geregistreerdeOrganisatie. Is het niet beter om hiervoor een specifieke associatie te voorzien van Geregistreerdpersoon naar GeregistreerdeOrganisatie?

**Comment by jensscheerlinck** [comment]
Agent is een abstracte klasse, waardoor in praktijk telkens één van zijn subklassen zal voorkomen, zoals persoon. Het dient slechts als ontkoppelpunt om niet telkens naar persoon, organisatie én hoedanigheid te moeten verwijzen.

In praktijk zal een applicatie informatie dus als volgt kunnen meegeven, in lijn met het Organisatie model én Persoon model (voorbeeld in JSON): 

```
{
	"@id": "{INSZ van persoon}",
	"@type": "GeregistreerdPersoon",
	"voornaam": "Jan",
	"achternaam": "Jansens",
	"heeftGeregistreerdeOrganisatie": "{Ondernemingsnummer}"
}
```
