### ISSUE TITLE
definitie richtlijn/procedure

### ISSUE THREAD

**Issue by nvdk** [Informatievlaanderen/OSLO-Discussion#58]
Het is nog steeds niet geheel duidelijk wat een richtlijn nu exact in houdt:
Aan de ene kant wordt er gesteld dat dit gaat om een leesbare versie van het formele kader. Deze versie richt zich op de burger en de ambtenaar die de dienstverlening verleent. 
Een 2e visie is een lokale implementatie van regelgeving (bv een lokaal richtlijn op basis van een federale wet). 

Dit zou moeten worden verduidelijkt.

PS: Een vriendelijke reminder dat er in de dienstverlening themagroep van 2 februari werd beslist om richtlijn ter hernoemen naar procedure.

**Comment by GeertThijs** [comment]
We mapten op http://purl.org/vocab/cpsv#Rule waarvan de definitie is:

> The Rule class represents a document that sets out the specific rules, guidelines or procedures that the Public Service follows. It includes the terms of service, licence, and authentication requirements of the Public Service. 

Maw: deze definitie is circulair. Dat probleem gaat niet weg als we de naam vervangen door Procedure. Zelf kozen we dus voor Guideline (Richtlijn) en CPSVAP gebruikt Rule (Regel).

TODO: verslag opzoeken waar beslist werd om Procedure ipv Guideline (Richtlijn) te gebruiken.

**Comment by GeertThijs** [comment]
Verslag bevestigt beslissing. TODO: Procedure ipv Richtlijn.

**Comment by GeertThijs** [comment]
DONE

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0
