### ISSUE TITLE
Waarom Gemeentenaam als klasse?

### ISSUE THREAD

**Issue by philipperutten** [Informatievlaanderen/OSLO-Discussion#62]
Er zijn twee constructies voor het aanduiden van een gemeentenaam: als data type property "gemeentenaam" en als object type property "heeft gemeentenaam" die linkt naar een object van de klasse "Gemeentenaam".

Wat is de meerwaarde van de constructie met object type property en klasse tov data type property? En waarom dan niet een link naar een object van klasse Gemeente (met property ‘naam’)?

**Comment by DieterDePaepe** [comment]
Deze dualiteit komt uit het INSPIRE-adres model, waar het OSLO adres op gebaseerd is. OSLO is dan weer op INSPIRE gebaseerd wegens verplichtingen naar Europa toe.

INSPIRE maakt het onderscheid tussen een platte weergave (onze data property) en een gestructureerde weergave (object property). De gestructureerde weergave laat in INSPIRE toe om extra informatie op niveau van de naam mee te geven (en niet de gemeente), zoals de uitspraak of delen van de naam. De platte weergave was er dan weer wegens simpliciteit.
