### ISSUE TITLE
Klasse "heeft geboorte" ?

### ISSUE THREAD

**Issue by philipperutten** [Informatievlaanderen/OSLO-Discussion#64]
Wat is het idee achter de volgende constructie: eigenschap “heeft geboorte” -> klasse “geboorte” met daarop eigenschappen datum en plaats?
Is geboorte enkel een cluster van geboorteplaats en geboortedatum?
Is een object van de klasse geboorte op zichzelf wel zinvol (en compleet) als er niet ook een referentie (link; object type property) naar een persoon bij zit?
Is het oké dat er vanuit meerdere personen naar éénzelfde geboorte verwezen kan worden? (twee personen kunnen op dezelfde dag en op dezelfde plaats geboren zijn, maar dat maakt het nog niet dezelfde geboorte)
Hetzelfde geldt voor de klasse overlijden en de overkoepelende klasse persoonsgebeurtenis: wat is er “persoons—“ aan die persoonsgebeurtenis zonder verwijzing naar een persoon? hoe onderscheid het zich dan van een klasse “gebeurtenis”?

**Comment by jensscheerlinck** [comment]
Momenteel zijn in deze constructie inderdaad enkel de attributen plaats en datum opgenomen. Daarnaast is de inverse relatie tussen de Persoongebeurtenis (Geboorte of Overlijden) en persoon er impliciet als de inverse relatie van "heeftGeboorte". 

De idee is dus dat conceptueel elke instantie van "Geboorte" slechts aan één persoon gelinkt is. Het nut van deze klasse komt voort uit potentiële uitbreiding. Bv. in de context van het Burgerloket wordt bekeken om op termijn ook bv. het geboortecertificaat te linken aan de klasse Geboorte.
