### ISSUE TITLE
Definitie "rol" bij "Partipatie" in Dienstencataloog AP

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#68]
Huidige definitie van rol in de klasse "Participatie":
"De rol die de deelnemer ad Publieke Organisatie speelt."

Is het mogelijk dat dit in de plaats moet zijn:
"De rol die de deelnemer ad Publieke ~~Organisatie~~ Dienstverlening speelt."

**Comment by dhaeneth** [comment]
Dat lijkt me idd een typo. Het gaat over de verschillende rollen die een bepaalde agent kan spelen binnen een bepaalde dienstverlening (anders dan ‘wordtUitgevoerdDoor’ en ‘heeftVerantwoordelijke’; vb. ‘gecontroleerdDoor’, ‘uitbesteedAan’, …).


Met vriendelijke groeten,

Thomas D’haenens
Product manager Wegwijs Organisatie, Productencatalogus
Afdeling Gegevens- en Dienstenintegratie

INFORMATIE VLAANDEREN
T of M 0472/21.52.93
thomas.dhaenens@kb.vlaanderen.be<mailto:thomas.dhaenens@kb.vlaanderen.be>

Boudewijnlaan 30, 1000 Brussel
Koningin Maria Hendrikaplein 70, 9000 Gent
www.vlaanderen.be<http://www.vlaanderen.be/> | www.agiv.be<http://www.agiv.be/>

Stel je vraag aan de overheid!
Bel gratis 1700 of surf naar www.vlaanderen.be<http://www.vlaanderen.be/>

//////////////////////////////////////////////////////////////////////////////////
[Beschrijving: Beschrijving: cid:image001.png@01D11E34.D603F010]

**Comment by jensscheerlinck** [comment]
Aangepast in meest recente versie:
https://data.vlaanderen.be/doc/applicatieprofiel/dienstencataloog#Participatie
