### ISSUE TITLE
Betontegels - Betonstraatstenen - Klinkers

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#75]
Betontegels -   Betonstraatstenen - Klinkers
--

onderscheid nog niet in   GGINO, wel nog voor te leggen aan projectgroep of klinkers ook niet horen bij   betonstraatstenen. Anders eventueel afmetingen erbij? Of generieker houden?
--

**Comment by tibaert** [comment]
"Klinkers" behoort tot GEBAKKEN_STRAATSTENEN (BestratingVerhardingTypeValue). Momenteel wordt het onderscheid tussen "afmetingen" gemaakt door 3 verschillende types van OnbegroeidVoorkomen: BedekkingOnbegroeidVoorkomen, BestratingOnbegroeidVoorkomen en GeslotenOnbegroeidVoorkomen.

**Comment by JorisVerbeken** [comment]
Ik ben geen expert, maar 'gebakken straatstenen' zijn nog iets anders dan klinkers. Gebakken straatstenen zijn blijkbaar erg duur. Wordt in Nederland erg veel geplaatst in de dorpscentra, en bij ons in Vlaanderen quasi nergens. Best nog even ter discussie voorleggen.

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Fysiekvoorkomen

**Comment by jensscheerlinck** [comment]
Besproken tijdens webcast op 26 september 2018
Voorstel van oplossing werd aanvaard:

Voor de taxonomische indeling van onbegroeid voorkomen werd gealigneerd op standaardbestek 250 van agentschap wegen en verkeer.

Geïmplementeerd in commit: https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/c0400668b0be709bf67f73f53e0ab5f67c7958c1

Resultaat: https://data.vlaanderen.be/doc/applicatieprofiel/onbegroeidvoorkomencataloog/
