### ISSUE TITLE
Toevoegen attribuut "erfdienstbaarheid" aan TerreinDeel

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#89]
Voorstel uit werkgroepsessie 1 om bij [TerreinDeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#TerreinDeel) een attribuut (true/false) toe te voegen om aan te duiden of een TerreinDeel een erfdienstbaarheid heeft.

**Comment by filipmahieu** [comment]
In wezen heeft dit te maken met leidingen, waterlopen,.. Maar voor zover ik weet is er geen gratis plan van die leidingen (Fluxys, Air Liquide, Navo-pijpleiding), maar wordt dit in de aankoopakte geschreven. Voor andere zijn de plannen dan weer wel gratis (Infrabel, Waterlopen), maar meestal wordt de zone van de erfdienstbaarheid niet in die lijst gegeven (zie VHA van de geklasseerde waterlopen).
Zou het niet beter zijn om een object 'Erfdienstbaarheden' in het leven te roepen? Alle objecten daarin vallen immers onder die erfdienstbaarheden. Zo weet men dan bij nieuwe objecten dat men dat niet mag vergeten.

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Terreindeel

**Comment by jensscheerlinck** [comment]
Besproken tijdens webcast op 26 september 2018
Voorstel van oplossing werd aanvaard:

Voorlopig niet toevoegen, nood aan afzonderlijke analyse rond welke informatie we willen bijhouden over erfdienstbaarheden.
