### ISSUE TITLE
Codelijst Nationaliteiten

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Discussion#9]
Bestaat er een officiële lijst met alle mogelijke nationaliteiten? Ideaal gezien houdt deze lijst ook nationaliteiten bij die niet langer bestaan.

**Comment by liesbetd** [comment]
Er zijn enkele opties: je kan je voor alles wat landen en nationaliteiten betreft baseren op de ISO country codes (3166) of op de lijst beheert door ADSEI. In principe is Buitenlandse Zaken hiervoor verantwoordelijk maar voor zover ik weet beheert ADSEI deze lijst voor hen. Het nadeel van ISO is dat er geen enkele mapping is met de nationale NIS codes. Fedict heeft contactpersonen voor dit project bij ADSEI (CountryCodes) dus wanneer dit nodig is, kan je via Fedict de juiste contactgegevens verkrijgen.

**Comment by bertvannuffelen** [comment]
Bekijk ook deze lijsten: die worden beheert en als die een domein bijna volledige afdekken dan denk ik dat deze uitstekende bronnen zijn.

http://publications.europa.eu/mdr/authority/index.html
Voor Landen is er de Country lijst. (En je hebt meteen ook 24 talige vertalingen ...)

mvg,

Bert

**Comment by KatrienLeire** [comment]
https://www.socialsecurity.be/portail/glossaires/dmfa.nsf/56d13fe0587c9d6dc1256b210060ae6a/2d0e5b5722f8538dc1256f5f0038c40c/$FILE/AN2004-1-Nl5.pdf  deze pdf maakt de link tussen NIS en ISO maar ik weet niet of er ook een structurele en actuele bron bestaat.

**Comment by jensscheerlinck** [comment]
Te implementeren: de Country NAL van het Europees Publications Office:

http://publications.europa.eu/mdr/authority/country/

**Comment by GeertThijs** [comment]
Wacht effe: is http://publications.europa.eu/mdr/authority/country/ wat we willen? Gaat over landen, niet over nationaliteiten. Mijn nationaliteit is niet België maar Belg.

**Comment by GeertThijs** [comment]
Oeps, slecht gekeken. Wel enkel in de XML-versie en de SKOS-AP-EU.

**Comment by GeertThijs** [comment]
Aangepast: enumeratie ipv GetypeerdeString in VOC & AP Persoon, met ap-codelist naar  http://publications.europa.eu/mdr/authority/country/ in AP.

**Comment by jensscheerlinck** [comment]
Fixed in https://github.com/Informatievlaanderen/Data.Vlaanderen.be/commit/50985b7c4e7307c80943137e6b991b3db3f31df0

**Comment by myosotisgit** [comment]
EU Open Data
https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/country
